### ISSUE TITLE
Add Groovy support

### ISSUE THREAD

**Issue by benniemosher** [houndci/hound#1003]

**Comment by teoljungberg** [comment]
Could you in more data for the description?

Some questions I have from my top on my head:
- Is there a groovy linter available for this?
- Could that linter run on Heroku?
- Is it possible to write a linter in Groovy for this?
  - Is there a way to talk via Resque(over Redis)

**Comment by gylaz** [comment]
We don't have any interest in supporting Groovy at this time.
