### ISSUE TITLE
Possible issue. Wrong "line too long".

### ISSUE THREAD

**Issue by jlgasparrini** [houndci/hound#1013]
Please, check this!
<img width="726" alt="screen shot 2015-12-16 at 10 11 02 am" src="https://cloud.githubusercontent.com/assets/4787484/11841666/9ffcb2b6-a3dd-11e5-9b9d-c91564cfd8ea.png">

**Comment by teoljungberg** [comment]
Could you share your `.hound.yml`, with the configured specified for `coffeescript`?

**Comment by jlgasparrini** [comment]
I'm sorry, but I haven't `.hound.yml` file.
Only I connect the repo with the app houndci.com, I don't know about settings for this.

**Comment by gylaz** [comment]
There hasn't been any updates on this recently. I'm going to assume this issue has been resolved.
