### ISSUE TITLE
Question: Linter Job Parameters diagram?

### ISSUE THREAD

**Issue by Potherca** [houndci/hound#1019]
I am looking at the docs on how to add a linter (it might happen, it might not... just looking for now).

Seeing as how I am usually to lazy to read/parse text and prefer images, I have the nasty habit of turning everything into a graph.

The result of this particular topic can be seen below. I was wondering if (something like) this would be of interest to you guys?

![](https://rawgit.com/potherca-contrib/hound/docs/doc/linter-job-parameters.svg)

**Comment by gylaz** [comment]
@Potherca I think this would be useful as diagram/image in the [CONTRIBUTING](https://github.com/houndci/hound/blob/master/CONTRIBUTING.md) doc.

**Comment by Potherca** [comment]
I'll send in a PR later this weekend. :+1:

**Comment by Potherca** [comment]
After careful consideration I've decided to spend my time on other things. If anyone wants to pick this up, my efforts thus far can be found at https://github.com/potherca-contrib/hound/tree/docs/doc

**Comment by thorncp** [comment]
Thanks for all your efforts @Potherca !
