### ISSUE TITLE
Add stylelint scss/css linting

### ISSUE THREAD

**Issue by ismay** [houndci/hound#1037]
[Stylelint](https://github.com/stylelint/stylelint) is a linter powered by [postcss](https://github.com/postcss/postcss), that can lint css as well as scss. It's kind of like the eslint of css linters, combining both style checks and error checks, and is completely modular (just like eslint). Since a lot of people are moving to postcss, I think this would be a nice addition to the list of hound linters.

**Comment by teoljungberg** [comment]
Thanks for reporting this. We have been talking with the creators of https://github.com/sasstools/sass-lint/  about replacing the current scss-lint with that.

We'll add this into the weighing process too

**Comment by ismay** [comment]
:+1: Cool, sounds good. I'd be really excited with the option of using postcss, the guys behind that project are putting a lot of effort into it and it should be just as easy to use for scss linting.

Thanks for considering it!

**Comment by davidtheclark** [comment]
@teoljungberg If you do consider stylelint, I'd appreciate any feedback you feel like providing, whether or not you decide to use it. Thanks.

**Comment by leandrogrillo** [comment]
any news about it? :(

**Comment by IschaGast** [comment]
Would be really nice

**Comment by pixelsonly** [comment]
@teoljungberg I'm very interested in `stylelint` support, this is the only thing holding be back from integrating Hound on a few projects.

**Comment by kaelig** [comment]
We'd be super interested in support for stylelint as well.

**Comment by athyuttamre** [comment]
+1. Perhaps one of the maintainers can lay out what needs to be changed, and one of us could send in a PR?

**Comment by kaelig** [comment]
Sorry to pull that card out but we're going to have to switch to another service to get stylelint support.

**Comment by gylaz** [comment]
@athyuttamre A PR would be welcome! Here are most recent commits that add Reek as a linter to Hound:

https://github.com/houndci/hound/commit/4852cc9d983bc49141103bcf062666ea3afaf9a3
and 
https://github.com/houndci/linters/commit/e382859cd19df79c7e73da2f980bde522a4c0cfb

Additionally, you can see how SCSSLint is implemented in this repo and in the `hound/linters` repo: https://github.com/houndci/linters/tree/master/lib/linters/scss_lint

**Comment by athyuttamre** [comment]
Thanks for doing this @blackjid and @gylaz! It's very much appreciated.
