### ISSUE TITLE
support HTML validation

### ISSUE THREAD

**Issue by afeld** [houndci/hound#1060]
I'm teaching [a JavaScript class](http://advanced-js.github.io/syllabus/), and am [trying out](https://github.com/advanced-js/syllabus/issues/63) Hound for doing style checking on their pull requests. One nice-to-have would be HTML validation – some options:

* https://validator.w3.org/source/
* https://validator.github.io/validator/
* https://github.com/ericbeland/html_validation
* https://github.com/jzaefferer/grunt-html

Admittedly, this would be less useful for projects that use templating, but figured I'd ask. Thoughts?

**Comment by teoljungberg** [comment]
Is there an HTML linter we can use for this?

**Comment by afeld** [comment]
See the links above :smile:

**Comment by teoljungberg** [comment]
Ah, I missed that. Sorry.

We'll definitely add it to our backlog and consider it.

**Comment by dionyziz** [comment]
Any updates on this?

**Comment by gylaz** [comment]
We don't have any immediate plans to support HTML. When we do, one of us will re-open this issue or create a new one.
