### ISSUE TITLE
.eslintignore file ignored by hound

### ISSUE THREAD

**Issue by kostos** [houndci/hound#1071]
I have simple `.eslintignore` file which works fine in all other environments except hound.
Is there way to disable Eslint or all hound linters for specific directory?

`.eslintignore` file contents:
```
spec/
vendor/
```

**Comment by danott** [comment]
Honoring `.eslinignore` would be very beneficial in a situation where I have no option but to vendor files.

![screen shot 2016-03-04 at 2 36 27 pm](https://cloud.githubusercontent.com/assets/185476/13542392/5590fd5e-e217-11e5-99b8-4fd88121d539.png) :dog2: :grimacing:

**Comment by tomasperezv** [comment]
This feature will be very important for us as well, we use eslint for linting our javascript files and without `.eslintignore` support we'd need to fallback to a different tool.

**Comment by dfournier** [comment]
Is there a way to know when it will be available on production?
