### ISSUE TITLE
RuboCop ActiveRecord conflict with Ruby Hash suggestion

### ISSUE THREAD

**Issue by croaky** [houndci/hound#1078]
> Use person.current_position[:location] = denver instead of person.current_position.update(location: denver).

I think RuboCop was trying to be helpful enforcing a Ruby Hash guideline but since I had an ActiveRecord relationship, the suggested change won't work. Maybe disable this rule in at least the thoughtbot style guide given we're mostly working in ActiveRecord environments?

**Comment by Koronen** [comment]
I think this has been resolved already, see #1076.

**Comment by croaky** [comment]
Great!
