### ISSUE TITLE
Vague error when linting with eslint

### ISSUE THREAD

**Issue by ismay** [houndci/hound#1081]
For this [PR](https://github.com/superwolff/metalsmith-layouts/pull/75) I'm getting the error: `We've encountered an error while reviewing your code.` Without any other messages.

Which doesn't tell me what's going wrong. Is it a configuration error, or has it found errors while linting with eslint?

**Comment by teoljungberg** [comment]
@ismay Could you email use at `hound@thoughtbot.com` and we'll discuss the issue further.

Some things we could need to debug the issue further:
- The contents of your `.hound.yml`
- The `config_file`'s specified for all of the language/linters.

Thanks!

**Comment by ismay** [comment]
No problem, email has been sent. Thanks!

**Comment by gylaz** [comment]
> We've encountered an error while reviewing your code.

Usually, this error means something erred unexpectedly Hound server-side.

**Comment by ismay** [comment]
@teoljungberg 

I've emailed the details, any news on what went wrong? Also, wouldn't it be easier to deal with troubleshooting in the issues instead of over email? That way if someone else encounters the same problems they'll be able to find the solution here.

**Comment by teoljungberg** [comment]
@ismay We have received the email, sadly we only work on Hound on Fridays. Which means that no-one has had time to look into the issue yet. When we do, we'll get back to you.

As far as the email vs issues question - we prefer discussing support issues over email. so we can ask for more details(that may or may not be sensitive).

**Comment by ismay** [comment]
> We have received the email, sadly we only work on Hound on Fridays. Which means that no-one has had time to look into the issue yet. When we do, we'll get back to you.

Cool, no rush, just wondering if it was received ok.

> As far as the email vs issues question - we prefer discussing support issues over email. so we can ask for more details(that may or may not be sensitive).

Ah ok, that makes sense. Thanks for getting back to me so quickly!
