### ISSUE TITLE
SECURITY.md out of date?

### ISSUE THREAD

**Issue by carols10cents** [houndci/hound#1087]
In the [current version of SECURITY.md](https://github.com/houndci/hound/blob/285bff807e32f77441d2c5de14265c876b408433/doc/SECURITY.md), it states:

> Your GitHub token is needed in order to fetch file content, comments, repo information and update Pull Request status. This token is stored in our Postgres database on Heroku and is base64 encoded using a protected key.

... but afaik base64 encoding is not encryption..... stating that you're safe because of base64 encoding is... false. 

The good news is the token  [**is** actually being encrypted](https://github.com/houndci/hound/blob/master/app/models/user.rb#L67) with `ActiveSupport::MessageEncryptor`, which by default uses [aes-256-cbc](https://github.com/rails/rails/blob/2af7338bdf32790a28e388a99dada84db0af1b5f/activesupport/lib/active_support/message_encryptor.rb#L35) _and then_ [base64 encodes it](https://github.com/rails/rails/blob/2af7338bdf32790a28e388a99dada84db0af1b5f/activesupport/lib/active_support/message_encryptor.rb#L9).

Another thing that looks out of date is the next section that says:

> To browse the portions of the codebase related to authentication, try greping for the following terms:
> 
> ```
> grep -R omniauth app
> grep -R github_token app
> ```

But I think recommending just `token` would be more comprehensive, since [that's now the field where the github_token is stored](https://github.com/houndci/hound/blob/9795417ec285722bcb9409362e3164ba6456b1be/app/controllers/sessions_controller.rb#L78) and github_token would be returned as well.

**Comment by gylaz** [comment]
Good eyes and research! Looks like we'll need to update it.

**Comment by malandrina** [comment]
Updated in https://github.com/houndci/hound/commit/1a514b591416f99511667b3f06a00822f4db1f35. Closing this.
