### ISSUE TITLE
Updating ActiveModelSerializers

### ISSUE THREAD

**Issue by bf4** [houndci/hound#1090]
So, I'm a maintainer of AMS and was wondering if you had any thoughts of updating to the [latest RC](https://rubygems.org/gems/active_model_serializers/versions) or any blockers if you've already discussed it :)

There doesn't appear to be any discussion in the repo here, and the version was hard-coded in https://github.com/houndci/hound/pull/536

**Comment by teoljungberg** [comment]
I would be happy to. What does the rest think? /cc @gylaz @thorncp

**Comment by thorncp** [comment]
:+1:
