### ISSUE TITLE
Builds never complete when both JShint and JSCS enabled

### ISSUE THREAD

**Issue by jbusser** [houndci/hound#1101]
Given a `.hound.yml` formatted with default configs:

```yml
javascript:
  enabled: true

jscs:
  enabled: true
```

Hound will begin, but never complete, a review of JavaScript code. With either option disabled, Hound reviews complete just fine.

I think the cause is this method:
```ruby
# app/services/complete_file_review.rb
def file_review
  @file_review ||= build.file_reviews.
    find_by!(filename: attributes.fetch("filename"))
end
```

When both JShint and JSCS are enabled, Hound does the right thing and creates a `FileReivew` job for each linter. Both linters complete successfully and both post their results to the correct queue. In my simple repo where I tried to understand this problem, I ended up with a `Build` that had a collection of two `FileReview`s, which I expected. However, when each linter completed and we invoked a `CompleteFileReviewJob` for each, the `.find_by!` query conditions weren't precise enough locate an appropriate `FileReview` row for each linter. This isn't a problem for any other languages because there is a 1:1 relationship between language and linter.

Because the second `FileReview` object never acquires a completed_at timestamp, `Build#completed?` always returns false when `BuildReport` gets invoked, thus no status update posted to Github.

The only solution I can come up with is passing a unique key that identifies each linter upon creation of a new `FileReivew` so that when `CompletedFileReviewJob`s execute, the above method would change to something like

```ruby
# app/services/complete_file_review.rb
def file_review
  @file_review ||= build.file_reviews.
    find_by!(
      filename: attributes.fetch("filename"),
      linter: attributes.fetch("linter_name"))
end
```

That feels like a pretty significant change, and I wanted to run it by you guys before throwing up a pull.

**Comment by jbusser** [comment]
I've been thinking about this some more, and I don't believe we need to change the database any to resolve this issue. Instead, we could change the implementation of `Linter::Base#file_review` so that we create the `FileReview` instance _before_ we call `build_review_job_attributes` and then change `build_review_job_attributes` so that it takes both a `commit_file` and a `file_review` arg.

From there, we can take one of two paths. The for the first path, we change `Linter::Base#build_review_job_attributes` so that we always include a `file_review_id` property in the payload we enqueue. This gives us consistent behavior across the board but it will also mean that each linter will need to be updated to pick off this `file_review_id` in the payload that it dequeues and then re-enqueues it for the `CompletedFileReviewJob` to consume.

The second path is to update only `Linter::Jshint` and `Linter::JSCS` to re-implement `build_review_job_attributes` to include a file_review_id: param. That introduces some specialized, and not consistent, behaviors by the linters but it also avoids having to change each and every linter.

Regardless of which approach you decide is better, the implementation of `CompleteFileReview#file_review` will could change to something like:

```ruby
# app/services/complete_file_review.rb
def file_review
  @file_review ||= 
    # look by file_review_id, which is new behavior
    (build.file_reviews.find_by(id: attributes["file_review_id"]) ||
    # otherwise, fall back to existing
    build.file_reviews.find_by!(filename: attributes.fetch("filename"))
end
```

**Comment by gylaz** [comment]
@jbusser Thanks for finding this, and spending time on figuring out solutions. I would be nice to know which `file_review` belongs to which linter -- for purposes of reporting and whatnot. What do you think of adding a `linter_name` column to `file_review`?

I like your second path -- it will allow us to update the other linters individually.

**Comment by jbusser** [comment]
@gylaz Thanks for your encouraging response. Hound already has `Linter::Base#name` defined, which derives from the name of the concrete class. I can append that to the file_review payload and store it in `file_reviews.linter_name`. I should have a pull ready this week.

FYI, I will also need to make changes to the JShint and JSCS linters to completely resolve this issue.

**Comment by gylaz** [comment]
That makes sense to me.

**Comment by gylaz** [comment]
#1102 Has been merged, that should address this issue. However, we'll be dropping support for JSCS soon due to it merging into ESLint: https://twitter.com/houndci/status/731219236459184128
