### ISSUE TITLE
ESLint: Support for javascript file

### ISSUE THREAD

**Issue by brgaulin** [houndci/hound#1106]
ESLint supports Javascript, JSON, and YAML.
http://eslint.org/docs/user-guide/configuring#configuration-file-formats

So today our project has something like this
```javascript
module.exports = {
    extends: "airbnb"
}
```

Which can't be read by hound. I may work on a PR for this later today, unfortunately, JS ones can't be verified I think by Ruby code(ExecJS doesn't support module exports)

**Comment by marcbachmann** [comment]
I suppose that might be more complicated on the service side because houndci probably doesn't want to execute javascript code because of security issues.
This is only a guess. I have no idea whether they already execute third party code on their server.

**Comment by teoljungberg** [comment]
@marcbachmann You're right about that.

This is sadly not feasable in the current landscape of Hound.
