### ISSUE TITLE
Support for custom cops?

### ISSUE THREAD

**Issue by joniles** [houndci/hound#1111]
Hi,

I have a custom Rubocop cop configured in `.rubocop.yml` using a configuration like this:
```yaml
require:
  - ./path/to/file.rb
```
where `./path/to/file.rb` is a file in the GitHub repo. This works fine locally, but appears to be ignored by Hound. Are custom cops supported by Hound? Thanks!

**Comment by teoljungberg** [comment]
Custom cops are not supported by Hound as of right now, we'll keep it in mind for the future.

**Comment by gylaz** [comment]
Executing custom Ruby on our servers is a security concern. It's not likely we'll support this feature, unless there is a safe way to do this.

**Comment by rmacklin** [comment]
@gylaz,
I can totally understand the security concern for not running custom cops on hound, but right now it seems that if you have a custom cop in your repository and your `.rubocop.yml` references it, hound won't just ignore the custom cop (which seems to be what @joniles reported), but will abort the rubocop linting entirely:

![image](https://user-images.githubusercontent.com/1863540/42468393-b0655770-8369-11e8-9275-6354ab0dea43.png)

which means that regular (not custom) cops won't run.

Is there any way for us to have custom cops in our repo (which our text editors can use), referenced by our `.rubocop.yml` and still have hound lint PRs using all the non-custom cops? Or is hound completely incompatible with any repository that has

```
require:
  - ./path/to/file.rb
```
in its `.rubocop.yml`?

**Comment by gylaz** [comment]
@rmacklin That's a great point! I do agree that Hound should still run regardless. Let me think about a solution for this.

**Comment by rmacklin** [comment]
Some ideas:
- Monkey patch this method: https://github.com/rubocop-hq/rubocop/blob/5ea73b3453a741b3ec05f781459741f39400c1a8/lib/rubocop/config_loader_resolver.rb#L9-L18 to be a no-op
- Remove the `require` key from the rubocop config before running rubocop

Are there other ideas you're thinking about @gylaz?

**Comment by rmacklin** [comment]
@gylaz I'm also curious about ways we could support custom cops without the security risk. Is there any low hanging fruit around providing the isolation necessary to combat the security risk? Can we learn from how CI services such as TravisCI and CircleCI handle the security implications of running custom code? (Or, would it be possible for hound to leverage those services since they already handle running custom code..?)

Our team has been enjoying hound for a while, but we recently added a custom cop (and would like to potentially add more in the future) and this issue has made that a real pain.

**Comment by gylaz** [comment]
@rmacklin Thanks for your suggestions.

> Remove the require key from the rubocop config before running Rubocop

This would be the easiest thing for us to do for us.

As for supporting custom cops... Currently, our architecture isn't flexible with running custom rules/linters. We don't leverage other CI services and I'm unfamiliar with how they sandbox their environments to run custom code.

The best thing I can think of right now, is if there was a gem with your custom cops, then we could install it on our end and run them from the gem. You'd have to ping us to update it, when you add additional custom cops. However, that doesn't seem like a very straightforward solution.

**Comment by arinhouck** [comment]
Is there any plan to revisit this? I find this a huge downside to HoundCI. I was very eager to deploy some very useful custom cops and just realized they were not functional past local.

Now looking at options to support through other services or consider a custom implementation.
