### ISSUE TITLE
ESLint Ignore Files

### ISSUE THREAD

**Issue by howdoicomputer** [houndci/hound#1114]
I'm trying to transition to Standard with Hound and have an `.eslintignore` file. I can't get it to work but... besides that, I noticed there isn't a field for providing an ignore file like there is with JSHint. Is this a planned feature?

**Comment by gylaz** [comment]
Thanks for reporting. It seems there's currently a bug in how Hound treats the ESLint ignore file (it erroneously looks for the `javascript` key in `.hound.yml`). I'm looking into getting this fixed soon.

**Comment by howdoicomputer** [comment]
Alright, no biggie. I'll just keep using my previous linter. Thanks for the response.

**Comment by gylaz** [comment]
This PR should resolve this: #1118

**Comment by howdoicomputer** [comment]
@gylaz Ah, cool. I actually don't think it will work out for my use case because `standard` uses `package.json` to define its ignored files and won't accept an `.eslintignore` file.

https://github.com/Flet/standard-engine/pull/104
https://github.com/feross/standard/issues/500

So I'll probably just keep with my custom linting rules because it's more convenient for me to integrate with CI and automated PR linting checks. Keep up the good work. I really like Hound and suggest it to people whenever I can.
