### ISSUE TITLE
Support ESLint 2.x

### ISSUE THREAD

**Issue by kostos** [houndci/hound#1115]
ESLint 2 was released in mid-February but HoundCI still doesn't support it.

BTW: [houndci Documentation](https://houndci.com/configuration#eslint) have link to ESLint rules documentation, this documentation valid for version 2.x, not 1.x

**Comment by teoljungberg** [comment]
Since we have https://github.com/houndci/eslint/issues/18 to track the progress, I'm going to close this.

**Comment by arxpoetica** [comment]
The link to issue 18 above is invalid. What version of ESLint is running on hound? (And how could I find out by just looking at the source code?)
