### ISSUE TITLE
ESLint issue

### ISSUE THREAD

**Issue by nneal** [houndci/hound#1126]
haven't heard back, so posting here

https://github.com/houndci/eslint/issues/23

**Comment by gylaz** [comment]
Hi @nneal,

I could be that Hound isn't picking up files due to their file extension. What file extension are you using?

**Comment by nneal** [comment]
Hey greg, we agree that that is the problem. the `jsx` files are the ones not working

along with the config shown above, we tried:

```
{      
  "env": {
    "jquery": true
  },
  "globals": {
    "_": true
  },
  "ecmaFeatures": {
    "jsx": true
  },
  "extends": "airbnb"
}
```

to no avail

**Comment by gylaz** [comment]
Hound will lint files ending in `.js` or `.es6` with ESLint. Are you using these file extensions?

**Comment by nneal** [comment]
No, we are using `jsx` since we're using react. Is it possible to enable checking of jsx?

**Comment by gylaz** [comment]
@nneal Hound should be linting `jsx` files now. Let us know if you're still experiencing issues.
