### ISSUE TITLE
Scala support?

### ISSUE THREAD

**Issue by mcmillan** [houndci/hound#1132]
Hello!

I'd be interested in adding support for linting Scala projects using [Scalastyle](http://www.scalastyle.org/) to Hound. This would probably have to take the form of a separate Scala linting service (using something like [Jesque](https://github.com/gresrun/jesque) to pick up jobs from the main Hound application) as is the case with Go, Swift etc.

Is that something anyone would be interested in, if I sink the time into creating the linter service?

**Comment by teoljungberg** [comment]
Hi @mcmillan.

We are working through stabilizing the current platform before adding any new linters.
So this maybe be relevant in the future, but not right now.
