### ISSUE TITLE
Option to group PR comments

### ISSUE THREAD

**Issue by jacknoble** [houndci/hound#1171]
This is an enhancement idea. Sometimes contributors submit large PRs which consistently violate a rule in many places in many files. As a result Hound will comment on the PR pointing out every single instance of the rule violation. Sometimes this results in > 30 comments. This really noisy and makes code review harder. It's also is often unnecessary since it likely just means the the PR author needs to change their own linter configuration. What I'd like to solve this problem is an option to group violations after the number of violations has exceeded a value specified in `.hound.yml`. 
e.g.

```
group_violations_after: 3
```

And then when there are 4 or more violations of 

> Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.

instead of commenting 4 times Hound would comment once at the location of the first violation with something like

> Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping. This violation occurred 3 more times.

The comment could also contain the file and line numbers of the other violations.

Thoughts? At a glance it seems relatively straight-forward to implement and I'd be willing to give it a try.

**Comment by gylaz** [comment]
This sounds pretty good.

For more context, we have a limit of how many comments Hound makes per review (`MAX_COMMENTS` setting and I think it's at 16 right now). It was a thing we did to get aroud the "Abuse" commenting rate limit imposed by GitHub.

I wonder if something like what's proposed by @jacknoble will be a better over-arching solution, and we can remove the `MAX_COMMENTS` setting.

**Comment by tbrisker** [comment]
Perhaps it would be possible to take advantage of the new "Review" github feature to group all comments as one review?

**Comment by teoljungberg** [comment]
@tbrisker We'd love to use the Review API, but sadly they haven't opened it up yet.

**Comment by tbrisker** [comment]
@teoljungberg looks like they have now released it, at least as a preview API: https://developer.github.com/v3/pulls/reviews/

**Comment by teoljungberg** [comment]
@tbrisker So we've noticed! There's a WIP PR for adding the feature, but there are some hinders in our ways. You can follow this progress in https://github.com/houndci/hound/pull/1262.

Since we're actively working on it, I'm going to go ahead and close this issue.
