### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by teoljungberg** [houndci/hound#1172]
The blockers from a quick glance seems to be:
- [ ] administrate (https://github.com/thoughtbot/administrate/issues/623)
- [ ] angular_rails_csrf (https://github.com/jsanders/angular_rails_csrf/pull/18)

**Comment by esparta** [comment]
Looks like both blockers are done. Doesn't it?

- administrate https://github.com/thoughtbot/administrate/pull/636
- angular_rails_csrf https://github.com/jsanders/angular_rails_csrf/pull/24

**Comment by teoljungberg** [comment]
Closed by eb5ded4
