### ISSUE TITLE
Enable Rubocop for files other than *.rb

### ISSUE THREAD

**Issue by benjaminoakes** [houndci/hound#1174]
I would expect Hound to check `*.rake` files, among others.  (See [a full list of what Rubocop suggests](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L11).)  I attempted to set this up, but it turns out that [Hound only looks at `*.rb` files](https://github.com/houndci/hound/blob/master/app/models/linter/ruby.rb#L4).  Can we extend that whitelist to support more than just `*.rb`?  We use a lot of Rake tasks in one project, so this would be a great help!

This is what I tried (which worked with `rubocop`, but not Hound):

```diff
diff --git a/.ruby-style.yml b/.ruby-style.yml
index 28b4f49..8933d44 100644
--- a/.ruby-style.yml
+++ b/.ruby-style.yml
@@ -1,4 +1,11 @@
 AllCops:
+  Include:
+    - '**/*.rb'
+    - '**/*.rake'
+    - '**/config.ru'
+    - '**/Gemfile'
+    - '**/Rakefile'
+    - '**/Guardfile'
   Exclude:
     - "vendor/**/*"
     - "db/schema.rb"
diff --git a/lib/tasks/bad_example.rake b/lib/tasks/bad_example.rake
new file mode 100644
index 0000000..f5c6a70
--- /dev/null
+++ b/lib/tasks/bad_example.rake
@@ -0,0 +1,4 @@
+desc "Example of a bad rake task (testing Rubocop)"
+task :bad_example => :environment do
+  woah_this_is_a_really_long_line_123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
+end
```

**Comment by treznick** [comment]
This also means that hound is not runnning for a lot of view templates. There is an argument to be made that automatic style checking in view templates is not the best idea, but there are some view templates (like `.rabl` files) that are pure ruby, and should be checked.

**Comment by benjaminoakes** [comment]
Another example: `*.jbuilder`

**Comment by BreahnaDavid** [comment]
https://github.com/houndci/hound/pull/1228

**Comment by benjaminoakes** [comment]
This may have been closed by #1228.  Once we have an example of `*.rake` files being supported, we can close this issue.  (I just had another pull request with bad tabbing in a Rake task, so I'm pretty sure Rubocop isn't running on them yet.)

**Comment by teoljungberg** [comment]
Closing since #1228 is merged.

**Comment by benjaminoakes** [comment]
This was merged two weeks ago, but has it been deployed?  I'm still not seeing `*.rake` files being processed by Hound.

**Comment by benjaminoakes** [comment]
I'm now seeing this working as expected.  Thanks!
