### ISSUE TITLE
Default Ruby config file missing

### ISSUE THREAD

**Issue by kstevens715** [houndci/hound#1185]
There is a default Ruby configuration file mentioned [here](https://houndci.com/configuration#ruby).

Clicking one of those links in that section results in a 404 not found error. I searched the hound repo and the only configuration file I see is the .ruby-style.yml in the root directory. I thought I saw a comment somewhere in the repo saying that was only the internal style file for the hound project itself and not the actual default used in projects using hound. Does hound use the default config from [Rubocop](https://github.com/bbatsov/rubocop/blob/master/config/default.yml)?

**Comment by blackjid** [comment]
Maybe the hound guys can correct me if I'm wrong. 

Hound used to use have a config in the `config/style_guides` which was removed in https://github.com/houndci/hound/commit/a1d76c2412fd00865feb56b781319f7eb29e2d97 after a lot of work where the configuration were moved to `thoughtbot/legacy_config` to maintain the behavior.

But the work is not completely ready, and the current goal is to remove any default configuration and use the linters default instead.

**Comment by gylaz** [comment]
@blackjid Is correct. New customers will use linter's default configurations (currently only true for Ruby and CoffeeScript). The documentation needs to be updated to reflect that.

**Comment by dcarral** [comment]
> New customers will use linter's default configurations

@gylaz Can existing customers somehow use default RuboCop configuration instead of yours?

**Comment by gylaz** [comment]
@dcarral Yes. Reach out to us via support widget from houndci.com
