### ISSUE TITLE
Violations found but checks are all still passing.

### ISSUE THREAD

**Issue by sushain97** [houndci/hound#1189]
My pull request has violations but Hound is still claiming all checks have passed? See below:

[![image](https://cloud.githubusercontent.com/assets/4211838/17849752/e5c8d03e-681f-11e6-81d3-2badcb588c5a.png)](https://github.com/goavki/apertium-html-tools/pull/71)

https://github.com/goavki/apertium-html-tools/pull/71

**Comment by blackjid** [comment]
You need to add `fail_on_violations: true` to the `.hound.yml` file in your repo to tell hound to fail the build.

**Comment by teoljungberg** [comment]
^ Correct. 

If you have any other questions @sushain97, please open another issue.
