### ISSUE TITLE
Hound not respecting ESLint (inline) file globals

### ISSUE THREAD

**Issue by arxpoetica** [houndci/hound#1209]
I can add them to the config file, but what if I want to specify only in the file, i.e., according to documentation: http://eslint.org/docs/user-guide/configuring#specifying-globals

Example:

```
/* global Ractive:false, require:false, recount, recoup, ratatat:false */
```

It's not respecting the above rule.

**Comment by rmerom** [comment]
What just worked for me is renaming .eslintrc to .eslintrc.json (and updating hound.yml accordingly)

**Comment by gylaz** [comment]
@arxpoetica Has this been resolved for you? I'm going to close this, but if it's still an issue, we can re-open.

**Comment by arxpoetica** [comment]
I don't know if it was ever resolved. I haven't used it for a while; haven't needed it. ;)
