### ISSUE TITLE
Use new GitHub PR review features

### ISSUE THREAD

**Issue by wolfy1339** [houndci/hound#1226]
Would it be possible to make hound set 'requested changes' to the PR whenever a warning is found, and when none are found approve the changes from the PR (maybe not, but rewuested changes would be really nice)

**Comment by teoljungberg** [comment]
There sadly isn't an API for us to use right now for the new review-based workflow, as soon as there is one we'll be on top of this.

**Comment by NuckChorris** [comment]
Looks like there's an API now!  https://developer.github.com/v3/pulls/reviews/

**Comment by teoljungberg** [comment]
@NuckChorris, it sure is! We've opened https://github.com/houndci/hound/pull/1262 that adds support for it.
