### ISSUE TITLE
Use RuboCop's auto-detection of Ruby version from `.ruby-version` 

### ISSUE THREAD

**Issue by dcarral** [houndci/hound#1230]
It seems like Hound CI doesn't take advantage of the RuboCop feature (added some months ago) which enables the automatic detection of the target Ruby parser version if a `.ruby-version` file is present in the project's root directory. Therefore, explicitly setting `TargetRubyVersion` to 2.2 is still needed in RuboCop config in order to avoid Ruby 2.3 being used.

**Comment by gylaz** [comment]
Hound processes individual files that it detects as changed. For security reasons, we don't clone the entire repository. Thus, `.ruby-version` isn't present when an individual file is linted.
