### ISSUE TITLE
Hound Badges

### ISSUE THREAD

**Issue by maschall** [houndci/hound#1249]
I like seeing circleci and travis statuses on Repos.  I'd like to display "Protected By Hound" proudly on my repo.

**Comment by jakecraige** [comment]
That's awesome! There's an awesome website [shields.io](https://shields.io/) that allows you to create a badge for anything you want.

I whipped up one for Hound you can use, or create your own 😄 

[![](https://img.shields.io/badge/Protected_by-Hound-a873d1.svg)](https://houndci.com)

**Comment by taitems** [comment]
For anyone who actually needs the source for the above:

```
![https://houndci.com](https://img.shields.io/badge/Protected_by-Hound-a873d1.svg)
```

Renders:
![https://houndci.com](https://img.shields.io/badge/Protected_by-Hound-a873d1.svg)

**Comment by salbertson** [comment]
Thanks @taitems! Here's the markdown we ended up using.

`[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com)`

**Comment by taitems** [comment]
Great, I’ll redact mine above and start using yours for consistency. I found this page via google and couldn’t see the actual code :)

**Comment by Musigwa** [comment]
Hey guys, I'm trying to integrate the HoundCI in my project. As you can see in the photo, I activated the repo on the HoundCI dashboard, but don't know how to get the badge so that I can ass it to my README.md file.
<img width="1200" alt="screen shot 2019-02-04 at 21 16 32" src="https://user-images.githubusercontent.com/29999424/52231359-6da7f100-28c2-11e9-84fa-a5449cd51d8b.png">

Can anyone help me how to do it?

**Comment by gylaz** [comment]
@Musigwa Just add the code from https://github.com/houndci/hound/issues/1249#issuecomment-407914400 to your `README.md`.

**Comment by Musigwa** [comment]
Thanks 

> @Musigwa Just add the code from [#1249 (comment)](https://github.com/houndci/hound/issues/1249#issuecomment-407914400) to your `README.md`.

Thanks, @gylaz, I'm going to add it, I'll let you know when it works.

**Comment by coolbeatz71** [comment]
> Thanks
> 
> > @Musigwa Just add the code from [#1249 (comment)](https://github.com/houndci/hound/issues/1249#issuecomment-407914400) to your `README.md`.
> 
> Thanks, @gylaz, I'm going to add it, I'll let you know when it works.

Hey @Musigwa. Is this solutions working?

**Comment by eonist** [comment]
I suggest: [![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com)
