### ISSUE TITLE
Hound ignores inherited rubocop config

### ISSUE THREAD

**Issue by cshaffer** [houndci/hound#1290]
As of a few days ago, at the time of posting this issue, it seems that inheritance of rubocop config no longer works. My guess is this was part of the refactor in this PR: https://github.com/houndci/hound/pull/1279

I've demonstrated the minimal steps to reproduce in the last two commits in this PR: https://github.com/cshaffer/hound-test/pull/1

**Comment by gylaz** [comment]
I believe https://github.com/houndci/hound/pull/1295 will resolve this issue.

**Comment by gylaz** [comment]
The related PR has been merged and code released today. Closing.
