### ISSUE TITLE
Delete resolved comments on next check

### ISSUE THREAD

**Issue by Kostronor** [houndci/hound#1306]
Following up on #1203 #1204 and #1214 

In [my current pr ](https://github.com/Kostronor/globalcorp/pull/2) I have some style violations but all are outdated. But Hound found one violation and I have no idea which one of them because all are collapsed.

Would be good to have resolved violations deleted immediately.

**Comment by Kostronor** [comment]
Since the pr will change, here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/644950/22335061/718d66c8-e3dd-11e6-9c81-25b957b50bc8.png)
There is one violation 5 minutes ago but i already fixed that in the last commit (which still reports one violation).

**Comment by gylaz** [comment]
We had this feature, but had to roll it back due to GitHub API limitations per user. Here's a related PR with explanation on why: https://github.com/houndci/hound/pull/1245

**Comment by Kostronor** [comment]
@gylaz now that hound does a review and batches comments, would it be possible to reconsider this feature?
