### ISSUE TITLE
TypeScript Support Status?

### ISSUE THREAD

**Issue by tam5** [houndci/hound#1308]
I see as of commit `ef17a11` TypeScript should be supported, yet I don't see it as part of any documentation and I cannot seem to have it triggered.

What is the status of support for TypeScript, what still needs to be done in order to enable it?

I'd be happy to contribute to adding support for TypeScript, if we could first understand what has already been done and what is missing...

Thanks!

**Comment by blackjid** [comment]
It should work if you enable it on your `.hound.yml` config file

```
tslint:
  enabled: true
```

Also, @gylaz commented here about enabling it as alpha, meaning no documentation for no https://github.com/houndci/hound/pull/1164#issuecomment-233079844

**Comment by tam5** [comment]
Do you mind having a look [here](https://github.com/tam5/hound-demo/pull/5) and seeing if I did something wrong trying to enable it?

It's a tiny demo with a pull request but while hound runs it does not pick up on any errors.

**Comment by gylaz** [comment]
@tam5 Were you able to figure out your issue? One thing that changed since then is we added a default config to Hound, without it users had to provide their own config.

**Comment by tam5** [comment]
@gylaz, thanks for following up.

I have not been able to resolve my issue. I just tried once again to create a demo with a pull request that will fail `tslint`, but Hound does not seem to pick up any issues.

It is possible I have done something wrong to configure, but it would be great to get confirmation on this so I know if I just made a mistake, or if I need to look into why the tslinter for hound isn't working yet.

[Here](https://github.com/tam5/hound-demo/pull/6) is my demo repository with my demo pull requests.

**Comment by blackjid** [comment]
What if you add a

`config_file: tslint.json` to the tslint settins in the `.hound.yml` file?

**Comment by blackjid** [comment]
What if you add the config file location to the `.hound.yml` file?

```
tslint:
     enabled: true
     config_file: tslint.json

```

**Comment by tam5** [comment]
Still doesn't seem to work. You can try it yourself: https://github.com/tam5/hound-demo

**Comment by gylaz** [comment]
I found the problem... TSLint was never even being used because we forgot to add to the master list of our linters. I've opened up a PR with a fix: https://github.com/houndci/hound/pull/1323

@tam5 you might just be the first person trying to use TSLint with Hound :)

**Comment by tam5** [comment]
makes sense.. thanks!

**Comment by tam5** [comment]
Has there been a release with #1323 yet?

**Comment by gylaz** [comment]
Not yet. We plan on a release on Friday and that will go out as well.

**Comment by gylaz** [comment]
It's been released. We'd to get any feedback about how it's working.

**Comment by blackjid** [comment]
👏

**Comment by tam5** [comment]
Yay, my initial test works! Thanks!!
