### ISSUE TITLE
Add support for babel-eslint and esprima eslint parsers

### ISSUE THREAD

**Issue by kamui** [houndci/hound#1309]
Our project uses babel and we've noticed that some babel transforms, like the spread operator, static class properties, and decorators, cause hound to comment on parse errors because it doesn't know how to read these transforms. These parse errors prevent any rule violations from being messaged.

In our local `.eslintrc` config we set the `"parser": "babel-eslint"`, which solve this problem. I don't see `babel-eslint` in your https://github.com/houndci/linters/blob/master/package.json, but I would hope the easiest solution would be to add those modules to your package.json file and allow repos to define `babel-eslint` (or `esprima`) as alternative eslint parsers to the default `espree`.

http://eslint.org/docs/user-guide/configuring#specifying-parser

**Comment by teoljungberg** [comment]
Hi @kamui!

Feel free the open a PR adding the two packages, we normally go about adding new packages by reading the code to see they aren't doing anything malicious that can hurt our users. But besides that, we're pretty flexible.

**Comment by kamui** [comment]
Thanks @teoljungberg, I opened a PR here: https://github.com/houndci/linters/pull/93

**Comment by thorncp** [comment]
Closed with #93. Thanks @kamui, this should be in production shortly.

**Comment by kamui** [comment]
@thorncp: Can you let me know when it ships or if it has already shipped? I'm still not seeing it work in my repo. Thanks!

**Comment by kamui** [comment]
If this has deployed, it unfortunately doesn't seem to work ☹️
