### ISSUE TITLE
credo/elixir linter

### ISSUE THREAD

**Issue by howdoicomputer** [houndci/hound#1312]
It looks like Elixir is a supported language as per the [Linters](https://github.com/houndci/linters) repository.

Any chance this'll go live?

**Comment by teoljungberg** [comment]
@howdoicomputer It will, we're still working out some quirks to it.

We'll send out an update once it's live and deemed stable.

**Comment by jakecraige** [comment]
Hey Tyler, it's currently in a private beta phase but you're more than welcome to turn it on and give it a shot. 

We've been using it internally on some apps and it has been working as expected. We just prefer to give new linters a bit of a trial run to catch any problems before taking them public.

You can enable it today in your `.hound.yml` like so:

```yml
credo:
  enabled: true
  config_file: .credo.exs # this is optional
```

Definitely let us know here or through our support channel if you do and have issues with it. We'd love to hear your feedback or of any problems you encounter with it.

**Comment by howdoicomputer** [comment]
@jakecraige @teoljungberg Ah, sounds great! I was a bit surprised when I saw that it wasn't supported since I've read Elixir articles coming out of Thoughtbot. Hound has been great for my Rails apps and I was hoping to sprinkle some of that goodness on my Elixir projects.
