### ISSUE TITLE
Can't make organization wide configuration work

### ISSUE THREAD

**Issue by blackjid** [houndci/hound#1315]
I want all my PRs to have jshint disabled and eslint enabled by default. I have a organization configuration setup for that. https://github.com/platanus/la-guia/blob/master/.hound.yml

But it doesn't work, jshint keeps adding comments to my PRs. And eslint is not doing anything (i can see the rescue queue for eslint never gets filled with a job)

I tried disabling jshint explicitly and also tried having the `resolve_config_conflicts` service to prioritize`eslint` as they were both enabled. But nothing changed.

Then I tried moving the configuration to one of my repos.
With the local config the eslint linter now to processes my prs but alongside with jshint. 

any idea?

**Comment by salbertson** [comment]
@gylaz @thorncp @teoljungberg @r00k any ideas?

**Comment by gylaz** [comment]
JSHint needs to be explicitly disabled, if you don't want it to run.

@blackjid Can you point to a specific PR where you have this setup and ESLint isn't using your org config?

**Comment by blackjid** [comment]
@gylaz 

https://github.com/blackjid/hound-styles/blob/master/.hound.yml
https://github.com/blackjid/hound-test/pull/3

i think the comments are from jshint and would expect a few comments from eslint.

**Comment by blackjid** [comment]
@gylaz just a quick poke, in case you missed it.. :)

**Comment by gylaz** [comment]
Thanks. I won't have time to look at this until next Friday.

**Comment by gylaz** [comment]
@blackjid Not sure if that is the problem, but you have `jshint: false` in your `.hound.yml` instead of:
```yaml
jshint:
  enabled: false
```

**Comment by blackjid** [comment]
@gylaz mm, I made a mistake on the demo repos I put together to replicate the issue..

I have the problem using the correct syntax.... and I've updated the styles in the demo to show that.. 
I opened another PR so it has clean comments from hound. blackjid/hound-test#4

Please!, me and my team have a few repos with dozens of comments from jshint when it should be disabled.... :(

**Comment by gylaz** [comment]
I figured out what is going on. Your repo (the one that wants to user org-level styles) still needs a `.hound.yml` file with specific linters enabled or disabled. HoundCI (currently) only fetches specific linter configs from org-level repos, but not the `.hound.yml`.

I do think it would be handy to not have to specify `.hound.yml` though, and we should support that. But currently, it doesn't.

So, just add a `.hound.yml` that specifies what is enabled/disabled and see if that solves your issue.

**Comment by blackjid** [comment]
Hey thanks!! You are totally right!!...

So yes, if I add the `.hound.yml` to the repo with the linters I want to enable and disable it works... It make sense to at least have that definition in the repo, and then as a convenience to have it in the general repo where the styles are (currently unsupported)

I have a couple of questions though, can you confirm I'm correct on this work?

- Hound will look in the repo that's being linted only for the enabled values of the linters?? But go to the org-wide conf repo to get other configurations for each linter?? That's why I can have the linters config files in `style/config/.eslintrc` for example... because the repo with the rules also have a `.hound.yml` the the `confif_file: style/config/.eslintrc` property... 
- The `ignore_file: ` property doesn't work in the org-wide conf right?
- Also I can report that is enough to just enable eslint and jshint is disabled... (the resolve_config_conflicts prioritize eslint )

**Comment by blackjid** [comment]
Thanks again @gylaz

**Comment by gylaz** [comment]
> Hound will look in the repo that's being linted only for the enabled values of the linters?? But go to the org-wide conf repo to get other configurations for each linter?? That's why I can have the linters config files in style/config/.eslintrc for example... because the repo with the rules also have a .hound.yml the the confif_file: style/config/.eslintrc property...

Sounds right to me.

> The ignore_file: property doesn't work in the org-wide conf right?

Yep. Something we should probably fix.

**Comment by gylaz** [comment]
Going to close this. Feel free to open issues for the things you'd like improved related to this conversation.
