### ISSUE TITLE
Use free SSL option on Heroku?

### ISSUE THREAD

**Issue by odlp** [houndci/hound#1319]
I noticed this app still uses the paid Heroku SSL addon. Could it be migrated to the new [free SSL option from Heroku](https://blog.heroku.com/ssl-is-now-included-on-all-paid-dynos)?

Apps:
- hound-production
- hound-staging

**Comment by teoljungberg** [comment]
@odlp Have it it, swing by our slack room `#hound` if you need any assistance.
