### ISSUE TITLE
Trying to install with homebrew, can't seem to bundle

### ISSUE THREAD

**Issue by MDes41** [houndci/hound#1320]
I can't seem to bundle passed capybara webkit.  I have qt8 installed and linked but it says Qtwebkit is no longer installed and I cannot install the capybara-webkit.  I am trying to contribute or look at the code but can't get passed this point.  Is there anything I am doing wrong? 

☯  ⤖ brew install qt5
Warning: qt5 is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
 ☯  ⤖ brew install qt5 --force
Warning: qt5-5.8.0_1 already installed, it's just not linked.
 ☯   ⤖ brew link --force qt5
Warning: Already linked: /usr/local/Cellar/qt5/5.8.0_1
To relink: brew unlink qt5 && brew link qt5

(add /usr/local/Cellar/qt5/5.8.0_1 to path in .bash)

 ☯  ⤖ source ~/.bash_profile
 ☯ ⤖ gem install capybara-webkit
Building native extensions.  This could take a while...
ERROR:  Error installing capybara-webkit:
	ERROR: Failed to build gem native extension.

    current directory: /.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0
/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20170223-32651-1flr6k1.rb extconf.rb
Info: creating stash file /.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0/.qmake.stash
cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake -o Makefile.webkit_server /Users/mdcomputer/.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0/src/webkit_server.pro 'LIBS += -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib' ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server
Project ERROR: No QtWebKit installation found. QtWebKit is no longer included with Qt 5.6, so you may need to install it separately.
make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3
Command 'make ' failed

current directory: /.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0
make "DESTDIR=" clean
cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake -o Makefile.webkit_server .rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0/src/webkit_server.pro 'LIBS += -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib' ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server clean
Project ERROR: No QtWebKit installation found. QtWebKit is no longer included with Qt 5.6, so you may need to install it separately.
make: *** [sub-src-webkit_server-pro-clean-ordered] Error 3

current directory: .rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0
make "DESTDIR="
cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake -o Makefile.webkit_server .rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0/src/webkit_server.pro 'LIBS += -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib' ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server
Project ERROR: No QtWebKit installation found. QtWebKit is no longer included with Qt 5.6, so you may need to install it separately.
make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3

make failed, exit code 2

Gem files will remain installed in .rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.12.0 for inspection.
Results logged to .rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-16/2.3.0/capybara-webkit-1.12.0/gem_make.out
 ☯  ⤖

**Comment by teoljungberg** [comment]
QT 5.5 was sadly the last version capybara-webkit was compatible with. As per their Wiki - https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#homebrew

If you install `qt55` from homebrew, you shouldn't have any issues installing capybara-webkit.

**Comment by pdeka** [comment]
Here https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit
