### ISSUE TITLE
Hound error on my PR: 'Error parsing config for: eslint.'

### ISSUE THREAD

**Issue by andela-fmustapha** [houndci/hound#1340]
Hello Teoljungberg, I created a pull request recently and everything seems fine with my .hound.yml and eslintre.json files but I am getting the error 'Error parsing config for: eslint.'. Please could you advice me on what to do. Kindly follow the link below to view the PR.

[view PR](https://github.com/andela/kakashi-cfh/pull/32)

-Faith M.

**Comment by teoljungberg** [comment]
Can you share the contents of your `.hound.yml` aswell as your `eslint` config file?

**Comment by andela-fmustapha** [comment]
Hi Teo, I just updated the my last comment with the link to my PR sorry for not doing this earlier. Kindly find links to the files you requested below;

[The PR](https://github.com/andela/kakashi-cfh/pull/32)
[.hound.yml file](https://github.com/andela/kakashi-cfh/blob/develop/.hound.yml)
[eslint file](https://github.com/andela/kakashi-cfh/blob/develop/.eslintrc.json)

**Comment by andela-fmustapha** [comment]
Hi Teo,
This issue has been fixed. 
The cause was that, on https://houndci.com,  the repository was not using repo specific  configuration file but an Organization wide-config file. The admin corrected this and everything now seems fine. 

Thank you
Faith M.

**Comment by teoljungberg** [comment]
Glad it sorted itself out, I'm closing this.
