### ISSUE TITLE
Hound ignores `scss_files` in .scss-lint.yml

### ISSUE THREAD

**Issue by joshlory** [houndci/hound#1341]
We have SCSS lint configured to only check certain files: `scss_files: 'dashboard/app/**/*.scss'`.

However HoundCI is warning on files that don't match that glob pattern: https://github.com/code-dot-org/code-dot-org/pull/14526.  Looking through our history, this repros as far back as August 2016: https://github.com/code-dot-org/code-dot-org/pull/9918#r73982444.

Hound seems to be respecting other settings in our `.scss-lint.yml` config, but not the `scss_files` option.  Thanks!

**Comment by joshlory** [comment]
We've disabled HoundCI for the time being.  Is there a workaround we can use to only lint certain SCSS files?

**Comment by XhmikosR** [comment]
@joshlory: Why don't you use a separate ignore file and feed it to `ignore_file` in `scss`?

**Comment by salbertson** [comment]
@joshlory any update on this?
