### ISSUE TITLE
Javascript aware of Flow type

### ISSUE THREAD

**Issue by hellowin** [houndci/hound#1345]
I use [Flow](https://flow.org/) on my projects and it seems HoundCI can't recognize it well.
Example PR: https://github.com/hellowin/kanca/pull/60#discussion_r113485597
Do you guys have any timeline for it?

**Comment by phyrog** [comment]
https://github.com/houndci/linters/pull/122 added the flowtype ESLint (and some others as well) plugin, so this should be working now.

**Comment by teoljungberg** [comment]
As that PR is merged, I'm going to close this issue.
