### ISSUE TITLE
Failed to load tslint.json: Invalid "extends" configuration value

### ISSUE THREAD

**Issue by th0r** [houndci/hound#1362]
Hi!

This comment appears after I push some `*.ts` files:

![image](https://cloud.githubusercontent.com/assets/302213/26622545/71c38e38-45f3-11e7-90c5-42b595357d0c.png)

Full error message:
```
Failed to load /tmp/d20170531-2228-1o35x4a/tslint.json: Invalid "extends" configuration value - could not require "tslint-eslint-rules". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
```

TSLint version: `5.3.2`
tslint-eslint-rules version: `4.1.1`

TSLint config:
```js
{
  "extends": [
    "tslint:recommended",
    "tslint-eslint-rules"
  ],
  "rules": {
    ...
  }
}
```

**Comment by teoljungberg** [comment]
Hi @th0r!

This would be resolved if you or the creator of https://github.com/houndci/linters/issues/131 would open a PR towards [houndci/linters](/houndci/linters) adding that package.

With that being said, I'm going to close this issue.

**Comment by th0r** [comment]
Made PR: https://github.com/houndci/linters/pull/132
