### ISSUE TITLE
Hound trying to read temp files

### ISSUE THREAD

**Issue by toppy42** [houndci/hound#1393]
Hi there!

Last hound started posting comments like this on every PR we opened, and every time we push.  
```
/tmp/d20170609-955-18g0mxh/.rubocop.yml: Style/DotPosition has the wrong name...
/tmp/d20170609-3791-1hjvm5v/.rubocop.yml: Style/DotPosition has the wrong nam...
/tmp/d20170609-10304-i6bz79/.rubocop.yml: Style/DotPosition has the wrong nam...
/tmp/d20170609-948-xaje80/.rubocop.yml: Style/DotPosition has the wrong names...
```

We don't have a tmp directory in our repo so I don't know what files it's trying to access.  Any idea what's going on?
Thanks

**Comment by thorncp** [comment]
@toppy42 Hound lints your files in a temp directory, which is what that path is referring to. You can effectively ignore it (we're working on stripping it out when reporting errors to avoid this confusion).

As for the underlying error, we recently updated to the latest version of Rubocop, which made some breaking changes to it's rules and you'll need to update your config. For reference, these are the changes we made: https://github.com/thoughtbot/guides/pull/496/files

**Comment by toppy42** [comment]
@thorncp got it, thanks!
