### ISSUE TITLE
ESLint ignore matching is incorrect

### ISSUE THREAD

**Issue by phyrog** [houndci/hound#1396]
The used `File.fnmatch` differs from the method used in `eslint` to find filter ignored files.

ESLint uses the npm package [`ignore`](https://github.com/kaelzhang/node-ignore), so a more accurate match would be the [`pathspec`](https://github.com/highb/pathspec-ruby) gem.

Problems the current approach causes:

- no support for `!` to negate matches
- `*` and `**` seem to be equivalent
- `foobar` and `/foobar` are not equivalent

**Comment by phyrog** [comment]
I'll create a test repository where the differences can be seen.

**Comment by gylaz** [comment]
Thanks @phyrog! The test repo would be helpful. Not sure how reliable the gem you linked to is, (1 watch, 1 star) but we can take a look into it or any alternatives.

**Comment by phyrog** [comment]
Here is the test repo: https://github.com/phyrog/hound-eslint-1497281215/pull/1

If you run eslint on that repo, only three files are linted:

- `file.js`
- `should-lint/file.js`
- `should-not-lint-2/should-lint.js`

Hound however seems to lint all 9 files. Note that not even the `**/should-not-lint-3/*.js` rule matches.

**Comment by gylaz** [comment]
I don't see a `.hound.yml` in that repo. Without it, by default, HoundCI will use JSHint to lint JS files. Ignore file must also be provided in `.hound.yml`.

**Comment by phyrog** [comment]
Oops, you're right. Added it now. Still there are some files that should not be linted.

**Comment by gylaz** [comment]
Thanks for flagging this and suggesting a fix! I opened #1397 to address this. Your feedback would be quite welcome!

**Comment by teoljungberg** [comment]
I'm closing this as #1397 seems to be merged.
