### ISSUE TITLE
What about C++?

### ISSUE THREAD

**Issue by alecive** [houndci/hound#1399]
As per title. This seems to me a great tool to coordinate work from multiple contributors, but as I work mainly in C++, it would be nice to add support for C++.

Thanks!

**Comment by gylaz** [comment]
Hi @alecive! That's something we'd love to explore. Are there any well-supported C++ linters that you can recommend?

**Comment by alecive** [comment]
@gylaz so this question is a bit tricky as to me there are no good C++ linters that check for style. There are tools like cppcheck or flint++ that are good, but check for limited things. 
cpplint gets closer, but it only checks against the google style guide.

What I would like to see is a bot/tool that automatically checks if external contributions (ie pull requests) are compliant with  my own style guide. The closest I got right now is to use clang-format and make the contributor manually run a style checker on his code, but that seems cumbersome to say the least.

**Comment by diegoferigo** [comment]
+1 for C++, I'm looking for exactly something similar for my projects. As @alecive wrote, `clang-format` looks the way to go, but it doesn't currently have a linter that tells you what kind of rule has been violated, at most it provides a `diff`.

**Comment by matt-chan** [comment]
I'd be interested in having Hound handle C++ as well. We have mixed Python/C++ projects which we run cpplint on for syntax checks. It ensures the google c++ style is followed.

In fact, someone has already easily added the feature to Hound in their own branch in 2014, but it looks like it wasn't merged back. http://hackerslab.aktsk.jp/technology/are-you-still-reviewing-that-pull-request/

I'd like to avoid maintaining a private instance of Hound like they did, so ideally it could be merged to master.

Thanks!

**Comment by tysongach** [comment]
Thanks for opening this issue. We've captured this in our internal backlog, so I'm going to close this.
