### ISSUE TITLE
HTML/CSS support?

### ISSUE THREAD

**Issue by kirkins** [houndci/hound#1405]
Would it be possible to support HTML and/or CSS?

**Comment by gylaz** [comment]
That is likely. Are there any particular linters for HTML or CSS that you can suggest?

**Comment by XhmikosR** [comment]
@gylaz: [vnu-jar](https://github.com/validator/validator) is the official HTML validator; it does require Java though.

**Comment by tysongach** [comment]
Thanks for opening this issue. We've captured this in our internal backlog, so I'm going to close this.
