### ISSUE TITLE
Allow eslint to lint Typescript files?

### ISSUE THREAD

**Issue by vovanmix** [houndci/hound#1417]
Hi!
We've been using Eslint to lint our typescript files in addition to Tslint, because Eslint has some great formatting rules that are missing in Tslint.
Is it possible to add support for that in Hound?

Eslint can parse Typescript files if `"parser": "typescript-eslint-parser"` is enabled in `eslintrc`. Otherwise it will error out. So this should not be enabled by default, and people should only enable this option if they have the parser added to `eslintrc`.

Because of that I'm thinking about either a `hound.yml` option for eslint, or creating a separate linter job, like `eslint-typescript`, that if enabled will run eslint on typescript files only.

Does it sound like a good idea?
Thanks!

**Comment by gylaz** [comment]
Hi @vovanmix,

I'm thinking if it's just an eslint plugin, then we can add it to our servers. Do I understand it right that it will only be used if it's configured correctly in the user's `eslintrc`? Or will it mess with all of the existing Hound's ESLint users?
