### ISSUE TITLE
Feature request: "[hound skip]" for a specific PR

### ISSUE THREAD

**Issue by ajb** [houndci/hound#1429]
Similar to the way that `[ci skip]` tells CircleCI to [skip a build](https://circleci.com/docs/1.0/skip-a-build/), it would be nice if `[hound skip]` or `[hound ignore]` could tell Hound to skip a certain PR.

Our use case: we're rewriting some large chunks of code automatically using [jscodeshift](https://github.com/facebook/jscodeshift), and it would be nice to not have a gazillion comments from Hound. :)

**Comment by tysongach** [comment]
We've captured this in our internal backlog, so I'm going to close this.
