### ISSUE TITLE
Repo model overrides Ruby's `private` method

### ISSUE THREAD

**Issue by x-yuri** [houndci/hound#1442]
https://github.com/houndci/hound/commit/27e82bdc9562707cbf5c4e07a785562964eab4d6#diff-0fa2d88e0cbaacf18f6096a7304430a1R14
http://ruby-doc.org/core-2.4.1/Module.html#method-i-private

That's unlikely expected.

**Comment by gylaz** [comment]
Is this causing an issue?

Ruby's `private` is a keyword, and we define the scope as a class method. The naming could be a bit weird, but functionality is as expected.

**Comment by x-yuri** [comment]
It being a keyword is not an issue. Do you understand what you're doing?

```sh
$ cat 1.sh
#!/usr/bin/env ruby
class A
  def self.private
    puts 'private was called'
  end
  private   # this line executes our `private` method
end

$ ./1.sh
private was called
```

As such your methods are no longer private.

And yes, it caused an issue. But I can't reproduce it right now. Supposedly, when `repo.rb` being loaded too early. Before connection to database is established.

**Comment by gylaz** [comment]
Good point and great catch! Thanks for the explanation. I'm going to pull that out.

**Comment by gylaz** [comment]
Merged and released.
