### ISSUE TITLE
Can't run application on my local machine

### ISSUE THREAD

**Issue by Giwery** [houndci/hound#1443]
Hello, I installed applciation to my local machine, then I created github OAuth app and copy Client ID and Client Secret to my .env. But when I login via github I have only nonstop load repositories list and every seconds create request:

{id: 1, refreshing_repos: true, subscribed_repo_count: 0, plan_max: 0, username: "my_github_username"}
id:1
plan_max:0
refreshing_repos:true
subscribed_repo_count:0
username:"my_github_username"

How can I fix this problem?

**Comment by sardaukar** [comment]
Are you running all the apps specified in `Procfile` or just the Rails app? Also, did you set all the remaining vars in the `.env` file? It still seems like it's trying to use "my_github_username" instead of your actual Github username.

**Comment by Giwery** [comment]
> Are you running all the apps specified in Procfile or just the Rails app?
Yes, I run resque workers and resque scheduler then rails app.

>  Also, did you set all the remaining vars in the .env file? It still seems like it's trying to use "my_github_username" instead of your actual Github username.
It's I changed my real github name to my_github_username in this issue.

**Comment by sardaukar** [comment]
Try inspecting the Redis queue at `/queue` to see what went wrong with the repo synchronisation job.

**Comment by igoroshchenko** [comment]
@sardaukar `/queue` ask me login and pass, where I can set or find it?

**Comment by Giwery** [comment]
@sardaukar /queue ask me login and pass, where I can find or set it?

**Comment by Giwery** [comment]
@sardaukar in `/queue` I find next error:
```
Class
 RepoSynchronizationJob (via ActiveJob)
Arguments
---
job_class: RepoSynchronizationJob
job_id: 0b287ce5-5494-446e-9401-864e77439a39
queue_name: high
priority: 
arguments:
- _aj_globalid: gid://houndapp/User/2
locale: en
attempts: 10
Exception
ActiveSupport::MessageVerifier::InvalidSignature
Error
ActiveSupport::MessageVerifier::InvalidSignature
```
What its mean?

**Comment by teoljungberg** [comment]
You also need to set `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`. If you read the CONTRIBUTING documentation, you will find that this is documented there.

Please re-open the issue if that contributing docs do not help you out.
