### ISSUE TITLE
stylelint doesn't respect ignores

### ISSUE THREAD

**Issue by XhmikosR** [houndci/hound#1454]
Discovered this in https://github.com/twbs/bootstrap/pull/24342

/CC @gylaz

**Comment by gylaz** [comment]
Thanks for opening this. We'll get someone to have a look at it, but should be similar to how `app/models/linter/jshint.rb` does it.

**Comment by XhmikosR** [comment]
@gylaz: I could have a look but my Ruby knowledge is pretty basic so it would be better and probably faster if someone else had a look.

**Comment by XhmikosR** [comment]
Do you think we can get this sorted in a sensible time frame? If not, I think we'll need to drop Hound for Bootstrap; we've had so many issues so far (no disrespect).

**Comment by gylaz** [comment]
Opened #1455 to address this.

**Comment by XhmikosR** [comment]
Thanks!

**Comment by gylaz** [comment]
This has been released.

**Comment by XhmikosR** [comment]
Thanks a lot for the quick fix, @gylaz!
