### ISSUE TITLE
Lint/ScriptPermission false positives

### ISSUE THREAD

**Issue by mhristof** [houndci/hound#1458]
Hi, im running hound in a private ruby repo and when i add a script, i get a complaint for `Lint/ScriptPermission`

When i make sure that is fixed (`git status` is clean in my dev env, im on the right branch, `ls -al` reports executable permissions), hound still marks it as an issue.

Any ideas if there is anything else i should be doing ?

**Comment by salbertson** [comment]
@mhristof it's been a while. Any update on this?

**Comment by mhristof** [comment]
sorry, ive moved on since then. @hlascelles might be able to help you on that

**Comment by salbertson** [comment]
@mhristof thanks
