### ISSUE TITLE
Incorrect eslint-plugin-prettier results

### ISSUE THREAD

**Issue by danseethaler** [houndci/hound#1461]
I'm working to get the `eslint-plugin-prettier` integrated into the [foreman](https://github.com/theforeman/foreman) repository but hound seems to be creating invalid prettier errors. 

### Example 1
The screenshot below shows an example of a fairly standard prettier change where the arguments to a function are broken up into multiple lines. However, Hound is reporting that prettier wants them on the same line.

![image](https://user-images.githubusercontent.com/11202705/32574088-1fea165c-c49e-11e7-9209-1981b11fdca3.png)

I added this file to the prettier sandbox to make sure I didn't have any invalid configuration that was affecting this. The expected results are shown [in this sandbox link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAwtAZgSwHMBXAJzgwFEoAvATwFs4AdKfBgBwlJg2A0hQCJchgC+GXKQgMMAcgT0mcgNyt2XHhgCCAEwCGHeKUnTZC2ozgBafQaNxS18vrAxrARgBsq1oOFkcAAU-HaGxkgYUHAA7jr2xkEAlOJJalCsAFZwAM4wAHTEUAwQYADWQXL5qHJprOqc3LwASnCuvFIy8i5uvmyNWvwlRbwSneaKVn0aTRgwEABSOdCmXRZKNvPWmctQ0wO8ACoQ+nkAMvh5q+bV+5q8MAAWRWXX3XC6xAAe1k8vd7N-ERAgBZUplADK81E43enx+JXK1jy3DgAMGrAwGHwbBg+H0ABsofp4AAaTEYHI4wgEuAg3I5fSEODEskUqlQGl0hlMuAAdXwTwuUEhMBJcHJUDGZnk1WOpxgFzy+QIXxggRyfUEV0RotRGAAvAI8MDyGDylDUUEANp-EUAXTqGSgulyYFI+AARsE5PLzpcYHJSRhkoaAHx8CmCypwTgwOistHB0MGiPAClY7W8FGiI26y3kII4wX4oli+BOrGZ6BXT0QL6GjDDWBBAA8fsVAcp0LgBuAObgElQYadGYwcC+HDgbiC8yW0CCda+SSS+XmIJJYEeEKghhyjwgMGS6SxYlHUCx0bkHK5TZ5zO74qDIZSqcjF6rWe7+rz4ILwRvWl6RyRlmUTStPxrXgl0bZsj3bE5-SuAc+wHIcR3SMcJynGcl3ycgXUcZIVRxXRKnyQlHEDVdaU5J5V3mAAhYIPAgs9MI-K9AIoJgQN5R94AwGJBUeDACRxMpnxTNMxy-AdYL-Hsgm44DQP5EThVFcUIOrKBa3rBSRjbDslWzHtUJ7dDzyrcdJ2nI88II11SGIggXUqfRagomAYBcuRHnIXBagYiBmMqQgIAgLl8kgBhahPVJ0nY1gQFJEAICMfAa2QUAOA9WABV0J5kAADgABjSsVPUK4qkAAJjS7iAEViEPOBkFwQkcglEBfP0fBxM5HAGAYfRkBAKBoHatLPVIVwyjgGAIQ4VxqWQXziB6nYvkYubykWiF9CYYV2qQTqCW6tKVtIbrSHGz19E9OgCWgVKQG6hh8HW0hNrS4husOR6cg6rqet0UoQYunqFUhy70uIGAOARurYcHMQgA) on lines 40-45.

### Example 2
In this instance Hound is reporting that spaces before line 120 need to be removed. I'm not sure why this would be reported but it's definitely not correct.

![image](https://user-images.githubusercontent.com/11202705/32574371-05d7496e-c49f-11e7-9c4a-d1fb0151d3c7.png)

You can see the PR [here](https://github.com/danseethaler/foreman/pull/2) for review. I'm using version `2.3.1` of the plugin just like the linters repo [here](https://github.com/houndci/linters/blob/master/package.json#L32).

I'd love to hear if anyone has ideas on this.

**Comment by alexandrebini** [comment]
I'm having the same issue of `Example 1` here

![](https://www.dropbox.com/s/pmcwwrttxcopbmc/79r_rzvk.png?raw=1)

@danseethaler Did you find any workarounds besides turning off some checks?

**Comment by danseethaler** [comment]
@alexandrebini unfortunately no - haven't received any support on this issue.

**Comment by salbertson** [comment]
@danseethaler so sorry for the slow response. Did you ever figure it out or do you have any update?

**Comment by danseethaler** [comment]
Thanks for reaching out @salbertson. We never got this resolved. I'm no longer working on the code base that having this issue. Sorry I'm not more help!

**Comment by gylaz** [comment]
I believe this is due to a mismatch in versioning of npm packages that we run on the Hound side. Since it's been several months since this was reported, I'm going to close this.

**Comment by schuylr** [comment]
We're still getting these kinds of errors. Can this be re-opened? What version is Hound running on their end?

![image](https://user-images.githubusercontent.com/12628715/71384620-5f34f780-25b0-11ea-995e-bc9c104a3f44.png)

**Comment by brendanoffer** [comment]
@gylaz I am getting this issue as well. I suspect the differences between our project prettier and hounds is due to version discrepancy. What version of prettier are you using for eslint 6.3.0?

**Comment by superslau** [comment]
@gylaz We're getting this as well. We're on Prettier 1.18.2. We may end up disabling this lint specifically for hound.

**Comment by gylaz** [comment]
Hound's ESLint `6.3.0` is using the following versions of plugins:

- prettier - 1.18.2
- eslint-config-prettier - 6.2.0
- eslint-plugin-prettier - 3.1.0

Any one of those mismatches could cause a difference with you locale.

We released support for ESLint `6.8.0` which will have the latest versions of all the related plugins.
