### ISSUE TITLE
Block pull request if violations was found

### ISSUE THREAD

**Issue by west0r** [houndci/hound#1462]
Hello. Thanks for Hound!

For now Hound not block merge button if violations was found. But I want to be able to merge only PR where all violations are fixed. Is there any way to change this behaviour?

**Comment by gylaz** [comment]
Yes, you can set `fail_on_violations: true` in your `.hound.yml` as documented [here](https://houndci.com/configuration).

**Comment by west0r** [comment]
Sorry, i did not see it. Thanks!
