### ISSUE TITLE
TSLint: false/positive when use field "object-literal-sort-keys" and keys separated by group

### ISSUE THREAD

**Issue by ArmandoAssuncao** [houndci/hound#1468]
Hi,

HoundCI is showing a false/positive warning `The key 'bar' is not sorted alphabetically`, when uses `"object-literal-sort-keys": [true, "ignore-case"]` in TSLint and the keys is **separated by group(blanklines)**
[About keys group](https://palantir.github.io/tslint/rules/object-literal-sort-keys/).

```
// tslint.json
{
  "rules": {
    "object-literal-sort-keys": [true, "ignore-case"],
  }
}
```

```
// index.ts
export default {
  foo: 'foo',
  
  bar: 'bar', // separated by blankline
}
```

Probably the resolution of this is update the tslint version.

Running tslint(v5.9.1) locally the warning is not show.

thanks

**Comment by gylaz** [comment]
We're now on `5.9.1`. Can this issue be closed?

**Comment by ArmandoAssuncao** [comment]
@gylaz, sure :+1:
