### ISSUE TITLE
add basic syntax validation for xml, yaml, json etc

### ISSUE THREAD

**Issue by devilj** [houndci/hound#1470]
a single character error in xml or yaml configuration file can be very hard to spot during code review, but could be a showstopper unless the project has 100% coverage, which is never true.

**Comment by tysongach** [comment]
That's a good idea, thanks for opening this issue. We've captured this in our internal backlog, so I'm going to close this.

**Comment by devilj** [comment]
@tysongach, any ETA?

**Comment by tysongach** [comment]
No, not at this time. It's not being actively worked on.
