### ISSUE TITLE
Add eslint-plugin-vue for linting Vue files with eslint

### ISSUE THREAD

**Issue by ruddzw** [houndci/hound#1484]
We are starting to move our codebase to Vue and I see that Hound does not currently lint Vue files. I think it should only require adding the `eslint-plugin-vue` plugin and setting the extensions of files that are linted by `eslint` to include `vue` files (similar to how you also lint `jsx` files for example).

As of now, when Hound tries to review our code, I see `Cannot find module 'eslint-plugin-vue'` as an error.

A similar plugin was added for issue #1406.

**Comment by gylaz** [comment]
Opened #1485 for this.
