### ISSUE TITLE
Allow setting `public_file_server` env value in production

### ISSUE THREAD

**Issue by zuzannast** [houndci/hound#1511]
Right now, the `config/environments/production.rb` hardcodes `public_file_server` value to false. I'd like to be able to set this value with the environment variable as in some cases I want it to be true. 
Let me know what you think about it I'll make a PR for that.

**Comment by gylaz** [comment]
Sure, I don't mind. We could do something like `config.public_file_server.enabled = ENV.fetch('SERVE_STATIC', false)` to allow for not setting the env value.
