### ISSUE TITLE
Broken link to default haml-lint config

### ISSUE THREAD

**Issue by Mehonoshin** [houndci/hound#1531]
Hey, folks!
You have 404 link here https://houndci.com/configuration#haml
It points to non-existing
https://raw.githubusercontent.com/houndci/linters/master/config/haml.yml

**Comment by gylaz** [comment]
Thanks for flagging this. We've decided to make that repository private, so the link is no longer reachable. We'll update the configuration page, to point it to [this gist](https://gist.github.com/gylaz/596b431373946f50e9881c5e275a6971).
