### ISSUE TITLE
Unable to use eslint with eslint-plugin-patternfly-react

### ISSUE THREAD

**Issue by sharvit** [houndci/hound#1540]
Hello,

We really enjoy using houndci in [theforeman](https://github.com/theforeman/foreman) project, +1 for that :+1: 

Yesterday, I tried to migrate our eslint configuration to be based on [eslint-plugin-patternfly-react](https://github.com/patternfly/patternfly-react/tree/master/packages/eslint-plugin) and houndci just don't recognize the `eslint-plugin-patternfly-react` package/module.

**The related PR:**
https://github.com/theforeman/foreman/pull/5566

**The error I receive from houndci:**

```
Some files could not be reviewed due to errors:

Oops! Something went wrong! :(
ESLint: 4.18.2.
ESLint couldn't find the plugin "eslint-plugin-patternfly-react". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make sure eslint-plugin-patternfly-react is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm i eslint-plugin-patternfly-react@latest --save-dev
If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Is there any way I can use 3rd-party eslint plugins?**
When I'm looking into the hounci code, it looks like the only plugins I can use are the one listed in the `package.json`.
Aren't you going to read my own `package.json` to install my own plugins?
Are you willing to receive a PR to hound that adds this particular plugin?

Thanks!

**Comment by gylaz** [comment]
Hi, @sharvit. I've just added `eslint-plugin-patternfly-react` to our back-end! We need to explicitly whitelist NPM packages on our side, but are more than happy to do it.

**Comment by sharvit** [comment]
Thanks @gylaz,
it's really great you could help and add the `eslint-plugin-patternfly-react` so fast :+1:
