### ISSUE TITLE
Unable to use tslint-no-unused-expression-chai with tslint

### ISSUE THREAD

**Issue by ejlangev** [houndci/hound#1542]
Here's the [package](https://github.com/kwonoj/tslint-no-unused-expression-chai). Saw this [issue](https://github.com/houndci/hound/issues/1540) which suggested the thing to do is to just open an issue.  Loving using hound so far, thanks for making it!

Let me know if there's additional info I can provide!

**Comment by gylaz** [comment]
Yes, we've added support for this package.

**Comment by ejlangev** [comment]
Awesome, thank you!
