### ISSUE TITLE
Change the default JS linter

### ISSUE THREAD

**Issue by TomasBarry** [houndci/hound#1548]
Is it possible to change the default linter for JS (JSHint) to Standard instead?

**Comment by TomasBarry** [comment]
Yes that is what I meant, has it been discussed at all?

**Comment by gylaz** [comment]
This is actually the first time we've heard of this particular linter. I don't see any reason we can't support it, but it would require us to do a bit of research. We've added this to our development roadmap, but I don't have any concrete dates.

**Comment by TomasBarry** [comment]
Actually, if you add
```json
...
"extends": [
    "standard"
],
...
```
to your .eslintrc it will apply Standard rules.

Thanks for the help
