### ISSUE TITLE
Client does not update object on response failure

### ISSUE THREAD

**Issue by trashhalo** [houndci/hound#1550]
```go
var resp client.Response
// finds results
err := client.Search(&resp, cfg, "node-xray", svc, "^package.json", 0, false, false)
// does not find results
err := client.Search(&resp, cfg, "http-shutdown", svc, "^package.json", 0, false, false)
// Expected Behavior - resp holds results from second call.
// Actual Behavior - resp still holding results from first call.
```

**Comment by gylaz** [comment]
Hi @trashhalo. I'm not sure I follow what the problem is. Is Hound not reporting an expected violation? Which of the lines would you expect a `golint` violation on?

**Comment by trashhalo** [comment]
@gylaz its not about go lint violation. its that the resp object says there is a match when there isnt because it has the match from the previous search run. I worked around it by creating to variables but I would have expected that client.Search would have put a empty map into the struct I gave it.

**Comment by trashhalo** [comment]
OMG. I made it on the wrong hound rep! Closing T_T
