### ISSUE TITLE
Passed and waiting at the same time

### ISSUE THREAD

**Issue by west0r** [houndci/hound#1555]
Hello. Thank you for hound. It's amazing tool, but I have a trouble. Github is waiting for hound status even if the status was report. What happened wrong?

![screen shot 2018-07-04 at 07 10 42](https://user-images.githubusercontent.com/8268115/42256428-e6e1e7f0-7f59-11e8-92ef-89a77af686f1.png)

Thanks in advance

**Comment by gylaz** [comment]
Hi @west0r. Some time back we renamed our GitHub app to capitalize the first letter, and that caused a mismatch in GitHub's settings. If you go to your repo's Settings > Branches, do you have any "Branch protection" rules set using `hound`?

**Comment by west0r** [comment]
@gylaz thank you! I found `hound` check, disabled it and enabled `Hound`)
