### ISSUE TITLE
eslint-plugin-filenames error

### ISSUE THREAD

**Issue by TaylorDaw** [houndci/hound#1567]
Hi, 

Thanks for the continued work on Hound, it's a great tool!

I recently attempted to start using ESLint, and came across an issue: 

```
Oops! Something went wrong! :(
ESLint: 4.18.2.
ESLint couldn't find the plugin "eslint-plugin-filenames". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make sure eslint-plugin-filenames is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm i eslint-plugin-filenames@latest --save-dev
If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

Is there any way `eslint-plugin-filenames` could be added to Hound's list of supported plugins? Please let me know if there is anything I can do to help, thanks!

**Comment by salbertson** [comment]
@TaylorDaw no problem, we can add the extension and let you know when it's available.

> Thanks for the continued work on Hound, it's a great tool!

**Comment by gylaz** [comment]
Support for this is now live.

**Comment by TaylorDaw** [comment]
Thanks @gylaz!
