### ISSUE TITLE
Missing eslint-plugin-no-unsanitized dependency

### ISSUE THREAD

**Issue by peritpatrio** [houndci/hound#1573]
Like in issue https://github.com/houndci/hound/issues/1540, we would need [eslint-plugin-no-unsanitized](https://www.npmjs.com/package/eslint-plugin-no-unsanitized) to be added to Hound’s backend.

Thanks!

**Comment by gylaz** [comment]
Thanks @peritpatrio . We've added the package now. Let us know if you're still seeing an issue.

**Comment by peritpatrio** [comment]
Thanks for adding it! Now there’s another one as well, so maybe it’s best to list them all at once.

Here’s our plugins used in our config:
```
eslint-plugin-import
eslint-plugin-jest
eslint-plugin-jsx-a11y
eslint-plugin-no-unsafe-regex
eslint-plugin-no-unsanitized
eslint-plugin-react
eslint-plugin-security
eslint-plugin-xss
```

**Comment by gylaz** [comment]
Looks like of those, we've already have most of them. The only ones missing are:
```
eslint-plugin-no-unsafe-regex
eslint-plugin-security
eslint-plugin-xss
```
I'll go ahead and get those added.

**Comment by peritpatrio** [comment]
Thanks @gylaz, much appreciated. 👍

**Comment by peritpatrio** [comment]
Any updates on these? Thanks!

**Comment by gylaz** [comment]
We've just released an update including these packages.
