### ISSUE TITLE
Invalid "extends" configuration value - could not require "tslint-config-standard".

### ISSUE THREAD

**Issue by bobvanderlinden** [houndci/hound#1574]
I'm getting the following error on pull requests in my repository:

```
Failed to load tslint.json: Invalid "extends" configuration value - could not require "tslint-config-standard". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
```

My `hound.yml` looks like:

```
tslint:
  enabled: true
  config_file: tslint.json
```

https://github.com/bobvanderlinden/probot-auto-merge/blob/d27d9943b063472a539a1ed4a1d17da9dafa1840/.hound.yml#L1-L3

And `tslint.yml` looks like:

```
{
  "extends": "tslint-config-standard"
}
```

https://github.com/bobvanderlinden/probot-auto-merge/blob/d27d9943b063472a539a1ed4a1d17da9dafa1840/tslint.json#L1-L3

`tsconfig-config-standard` is in `package.json` under `devDependencies`:

```
"tslint-config-standard": "^8.0.0",
```

https://github.com/bobvanderlinden/probot-auto-merge/blob/d27d9943b063472a539a1ed4a1d17da9dafa1840/package.json#L46

I *think* this started happening since I upgraded `tslint-config-standard`, but I'm not 100% sure.

**Comment by gylaz** [comment]
Thanks @bobvanderlinden. We've added the package now. Let us know if you're still seeing an issue.
