### ISSUE TITLE
Stylelint configuration format is invalid

### ISSUE THREAD

**Issue by filidorwiese** [houndci/hound#1581]
We're preparing to move from scss_lint to stylelint. Due to having a shared code-base with another team we're using the `module.export` configuration option that [stylelint supports](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md).

Sadly, it seems that hound does not:

```
Hound — ./client/stylelint.config.js format is invalid
```

Our .hound.yml:
```
stylelint:
  config_file: ./client/stylelint.config.js
  enabled: true
```

Stylelint works when I run it locally on CLI:
```
$  ./node_modules/.bin/stylelint 'client/src/**/*.scss' --config ./client/stylelint.config.js
```

Or am I configuring hound incorrectly?

**Comment by filidorwiese** [comment]
Bump...

**Comment by filidorwiese** [comment]
Makes perfect sense. Thanks for your help. I'll close this PR.

**Comment by emilkarl** [comment]
We are seeing this issue randomly now. Even in branches where not changes to this file has been made.
