### ISSUE TITLE
Add eslint-plugin-wyze plugin support

### ISSUE THREAD

**Issue by wes-r** [houndci/hound#1591]
I recently added `"wyze/sort-destructuring-keys": "error"` to my project in order to force my destructuring objects to be sorted. This depends on [eslint-plugin-wyze](https://github.com/wyze/eslint-plugin-wyze) which I believe needs to be added to the top package.json in order for houndci to not complain?

**Comment by salbertson** [comment]
@wes-r no problem, we'll get it added soon and let you know.

**Comment by gylaz** [comment]
Support for this is now live.
