### ISSUE TITLE
The timestamp of docs on intercom are not updated - stuck with "Updated over a week ago"

### ISSUE THREAD

**Issue by kinopyo** [houndci/hound#1595]
Hi there.

I found the docs on intercom (e.g. https://intercom.help/hound/configuration) has the fixed timestamp of "Updated over a week ago":

![configuration___hound_help_center](https://user-images.githubusercontent.com/184520/46989026-5e940c00-d136-11e8-9227-20b12b1c3635.png)

I visit those docs occasionally to check certain linters' versions and found the fixed timestamp not that helpful. No real harm but hope we can get a more up-to-date timestamp to show the progress 🙏 . "Updated 3 months ago" I think is more accurate, although it shows no activities, it doesn't give the false hope if you don't read carefully.

Thanks.

**Comment by salbertson** [comment]
@kinopyo we are using Intercom to host these pages, so I'm not sure we have much control over those time descriptions. We are planning to create a single page with all the linter versions in one place, so that might help. I'll let you know when that ready.

**Comment by kinopyo** [comment]
@salbertson Thank you for the update! Looking forward to that! 👍

**Comment by gylaz** [comment]
We now maintain http://help.houndci.com/configuration/supported-versions that documents supported versions by Hound.

**Comment by kinopyo** [comment]
@gylaz thanks for letting me know! Great job with recent various improvements! :+1:

**Comment by salbertson** [comment]
Thanks @kinopyo!
