### ISSUE TITLE
Support for eslint-plugin-ramda in hound

### ISSUE THREAD

**Issue by maxpollack** [houndci/hound#1596]
We're currently using `eslint-plugin-ramda` on our local machines, we'd like it to be part of our PR process on github as well.

I saw mentioned in another issue that you can explicitly whitelist npm packages for hound - would someone mind whitelisting this one for us?

**Comment by maxpollack** [comment]
Thank you very much for this!

**Comment by maxpollack** [comment]
Not to bother but is there any update on this? We've had a PR with this dependency on hold for a while.

**Comment by gylaz** [comment]
The plan is to release it later today.

**Comment by gylaz** [comment]
The support for this should be live now. Let us know if you still see an issue with it.

**Comment by maxpollack** [comment]
Thank you so much for getting to this! Great support from your team. You're awesome!

**Comment by gylaz** [comment]
Sorry about that. Can you try it again? I believe we've got it this time :)
