### ISSUE TITLE
Interest for Brakeman, ERB Lint and bundler-audit?

### ISSUE THREAD

**Issue by aldesantis** [houndci/hound#1599]
I'm opening this issue to determine if there's interest for supporting Brakeman, ERB Lint and bundler-audit in Hound. Currently, [we](https://github.com/nebulab) are running all of our linters as part of our CI process, but we'd love for them to be centralized and we'd be very happy to switch to Hound if they were available. If this is something the Hound team is willing to add, we can work on the integration.

**Comment by salbertson** [comment]
@aldesantis sounds awesome! I think all of those would be great additions to Hound.

**Comment by aldesantis** [comment]
@salbertson cool! We'll start thinking about this next week. Could you give us any indications as to where we should start from or any other advice?

**Comment by gylaz** [comment]
@aldesantis [CONTRIBUTING](https://github.com/houndci/hound/blob/master/CONTRIBUTING.md) has information on how to setup the repo locally and how to add a new linter. If you'd like to add a new linter/tool, we can add you as a contributor to you private `linters` service.

**Comment by aldesantis** [comment]
@gylaz thanks, I have already been added to the repo. I’ll start on this next week!

**Comment by salbertson** [comment]
@aldesantis it's happening. https://github.com/houndci/hound/pull/1641 Thank you for the help with adding ERBLint!

**Comment by gylaz** [comment]
Erb Lint is now supported and can be enabled via `.hound.yml`
```yaml
erb_lint:
  enabled: true
```
We can open a separate issue for Brakeman if there's still interest. Going to close this one for now.
