### ISSUE TITLE
Random Hound errors resulting from spaces in folder names?

### ISSUE THREAD

**Issue by robertmryan** [houndci/hound#1616]
We've been using Hound for a while in an iOS project for a while, but we're suddenly getting random errors in our GitHub `houndci-bot` reviews in our builds:

> Some files could not be reviewed due to errors:
>
> Loading configuration from '.swiftlint.yml` 
>
> ![hound](https://user-images.githubusercontent.com/1530768/47450370-ec48aa80-d779-11e8-9f02-3b1325b481aa.png)

The curious thing is that the path `./Source/Login/Sign In/EnterPasswordViewController.swift` seems to be broken up into two different paths, `./Source/Login/Sign` and `In/EnterPasswordViewController.swift`. 

I don't know whether this is the root of the problem (though it's been processing this same file structure for a long time so it's curious that the problem is appearing now ... and the file that it reports this error seems to change from build to build) or whether this error message is a red herring and whether there's some other issue.

Sure, we could go through our project and remove these longstanding folder names with spaces (how is this still a thing?), but I hate to do that if this is just some temporary Github/Hound bug. How can we diagnose the real issue?

**Comment by gylaz** [comment]
We've been seeing some inconsistencies between the Mac and Linux versions on of SwiftLint.
It looks like the issue is related to `Sign In` having a space between it.
We'll try go get a solution for this out and update this issue.

**Comment by gylaz** [comment]
This has been released. Let us know if this error shows up again.

**Comment by robertmryan** [comment]
It looks like the problem is resolved! Thanks for jumping on this.
