### ISSUE TITLE
Hound comments "unexpected token kRESCUE" on Ruby 2.5 code

### ISSUE THREAD

**Issue by ruddzw** [houndci/hound#1628]
I get the following error from Hound on some Ruby 2.5 code that I'm committing: `unexpected token kRESCUE`. `unexpected token tASSOC` also shows up on some lines. These pop up in areas where I have updated our code to work with the cop `Style/RedundantBegin` with Ruby 2.5 `do/end` syntax. Something like changing:

```ruby
do_something_with_a_block do
  begin
    do_a_thing
  rescue StandardError => e
    do_another_thing(e)
  end
end
```

to:

```ruby
do_something_with_a_block do
  do_a_thing
rescue StandardError => e # hound comments on this line
  do_another_thing(e)
end
```

In our project, we have set `.ruby-version` to `2.5.1`. I also see that rubocop runs fine by itself (version `0.54.0`) -- only Hound seems to have an issue with these changes. Do you have any ideas on why Hound might be complaining? It's as if Hound is trying to parse our code with an older version of Ruby.

**Comment by gylaz** [comment]
We offer an upgrade to RuboCop `0.59.2` in which we support Ruby 2.5 syntax.

You can upgrade by specifying it in your `.hound.yml`:
```yaml
rubocop:
  version: 0.59.2
```

**Comment by ruddzw** [comment]
That worked! Thanks for the info. Is there somewhere that lists what ruby versions are compatible with which rubocop versions? 0.54.0 worked fine locally with 2.5.

**Comment by gylaz** [comment]
There isn't really a list. I think we just forgot to make Ruby 2.5 syntax the default of `0.54.0` (which I'll do).
I believe you can always tell Hound to use the specific Ruby syntax by adding this to the rubocop config:
```rb
AllCops:
  TargetRubyVersion: 2.5
```
