### ISSUE TITLE
Upgrade flake8 from v3.5.0 --> v3.6.0?

### ISSUE THREAD

**Issue by cclauss** [houndci/hound#1639]
https://intercom.help/hound/configuration/flake8 says that flake8 is struck at v 3.5.0 while last month [v3.6.0 was released](http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html).

https://github.com/houndci/hound/pull/1459 says that the flake8 version is hardcoded (where?j because it does not change often but it has changed recently.  Can we get the current version in hound or request it on-the-fly as is done in https://intercom.help/hound/configuration/linter-versioning ?

Is https://github.com/sigmavirus24/houndci-python the engine for Python/flake8 or is that elsewhere?

**Comment by gylaz** [comment]
Is the `3.6.0` backwards compatible?

I think it probably makes sense to add support for `3.6.0` as an opt-in, and keep `3.5.0` as the default for now.

**Comment by salbertson** [comment]
> I think it probably makes sense to add support for 3.6.0 as an opt-in

I agree.

**Comment by cclauss** [comment]
I don't see why users would want to use older versions given the release notes for the current version.
* https://flake8.readthedocs.io/en/latest/release-notes/3.6.0.html

**Comment by gylaz** [comment]
@cclauss Good point.

The reason we introduced an opt-in strategy for linters, is to avoid switching the rug from under all of the existing users of Hound. Certain linters like RuboCop and ESLint will often break compatibility by renaming rules, or completely removing them.

However, in this case it looks like a 3.6.0 of Flake8 is a safe, straight-forward upgrade, and can be done for everyone.

@salbertson thoughts?

**Comment by salbertson** [comment]
@gylaz fine with me. 👍

**Comment by cclauss** [comment]
OK so now that we are agreed on the upgrade, where do changes need to be made?  I could not find the right places in this codebase.

**Comment by gylaz** [comment]
We've upgraded Flake8 to 3.6.0.

**Comment by cclauss** [comment]
https://intercom.help/hound/configuration/flake8 still says 3.5

**Comment by gylaz** [comment]
Updated, thanks.
