### ISSUE TITLE
How to ignore .min.js files ?

### ISSUE THREAD

**Issue by Seluj78** [houndci/hound#1648]
Is there a way to specify a list of files to ignore in the `.hound.yml`?

**Comment by salbertson** [comment]
@Seluj78 are you asking about a global ignore list?

**Comment by Seluj78** [comment]
I am

**Comment by gylaz** [comment]
Which linter are you using for JS?

**Comment by Seluj78** [comment]
Oh alright, then I suppose I have to specify ignoring the file I want on the linter !

The thing is, what I'm making is using a flask backend, and then bootstrap frontend so I don't know what to use 🤔

Flake8 for sure

**Comment by gylaz** [comment]
You probably want to use ESLint for your front-end JS code (if any), for CSS you can use either https://github.com/stylelint/stylelint or https://github.com/sasstools/sass-lint, both of which Hound supports.

**Comment by Seluj78** [comment]
Thanks a lot ! I was about to close this :)
