### ISSUE TITLE
Hound does not lint test files as expected

### ISSUE THREAD

**Issue by tutugodfrey** [houndci/hound#1662]
I am in the middle of completing a setup with eslint and prettier. I define my eslintrc and prettierrc files as shown below
`eslintrc.json`
```
{
  "extends":[ "airbnb-base", "prettier"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error",
    "max-len": ["error", 80]
  },
  "env": {
    "node": true,
    "es6": true,
    "mocha": true
  }
}
```
`pretttierrc.json`
```
{
  "singleQuote": true,
  "trailingComma": "all"
}
```
I run the lint command locally and clear all linting errors flagged. However, when I push to Github hound flag the following errors on my tests file
`Replace 'message' with "message" prettier/prettier`

I can seem to understand why hound fails to respect the linting rules for the test file. Please give suggestion on how to get over the issue.

**Comment by gylaz** [comment]
Hound doesn't know anything about Prettier config file. It's only using ESLint and its config. Prettier is supported with its default rules, Hound doesn't know about its config file. 
You can do something like this in your `eslintrc.json`:
```js
"rules": {
  "prettier/prettier": ["error", {"singleQuote": true, "trailingComma": "all"}]
  ...
}
```
