### ISSUE TITLE
Updating .ruby-version

### ISSUE THREAD

**Issue by TomasBarry** [houndci/hound#1668]
Currently, the `.ruby-version` specified is [2.5.1](https://github.com/houndci/hound/blob/master/.ruby-version#L1).

The latest version stable version of Ruby is [2.6.0](https://www.ruby-lang.org/en/downloads/).

Are there intentions to upgrade, or is it possible for a repo to indicate to what Ruby version to target? Perhaps in the `.hound.yml` given the concern [raised here](https://github.com/houndci/hound/issues/1230)?

**Comment by gylaz** [comment]
@TomasBarry We're upgrading our linter services to 2.6.1 (to be released next week). There is a setting in RuboCop that allows to specify a ruby version: https://rubocop.readthedocs.io/en/latest/configuration/#setting-the-target-ruby-version

The `houndci/hound` doesn't actually run the linters, so upgrading ruby isn't as necessary. Though, we'll want to eventually upgrade it here as well to stay current (help on this front is always welcome 😄).
