### ISSUE TITLE
Please add support for eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by drewtonynguyen** [houndci/hound#1671]
Hello, I am receiving the following error from hound-ci after adding [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks) to my project's eslint configuration.
```
Oops! Something went wrong! :(
ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-react-hooks". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make sure eslint-plugin-react-hooks is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm i eslint-plugin-react-hooks@latest --save-dev
If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

Could this package be whitelisted for hound-ci? Thank you!

**Comment by gylaz** [comment]
Hi. Yes, we can white list this one. I'll update this issue once we've released a version with it.

**Comment by gylaz** [comment]
Added and released.

**Comment by gggritso** [comment]
Heya! we’re running into some issues with this plugin:

```
Definition for rule 'react-hooks/exhaustive-deps' was not found react-hooks/exhaustive-deps
```

I’m wondering if it’s out of date in Hound, because other rules from that package are working great!

**Comment by gylaz** [comment]
@gggritso Can you reach out to us via the help widget on houndci.com and we'll help you out.
