### ISSUE TITLE
Please add support for eslint-plugin-ember

### ISSUE THREAD

**Issue by jordanbyron** [houndci/hound#1674]
👋 Hi Hound peeps!

I've got another eslint package I was hoping you could whitelist: [eslint-plugin-ember](https://www.npmjs.com/package/eslint-plugin-ember).

Thank you! 🐶 ❤️

**Comment by gylaz** [comment]
We certainly can. I'll update you once we get this released.

**Comment by jordanbyron** [comment]
Thanks so much Greg!

**Comment by gylaz** [comment]
This has been released.
