### ISSUE TITLE
Whitelist request for @hesburgh-wse/eslint-config-hesburgh

### ISSUE THREAD

**Issue by danthewolfe** [houndci/hound#1678]
We recently created our own eslint-config that we are using on multiple open source projects. I was hoping that this could be whitelisted.

NPM link: https://www.npmjs.com/package/@hesburgh-wse/eslint-config-hesburgh

GitHub link: https://github.com/ndlib/eslint-config-hesburgh

**Comment by gylaz** [comment]
@danthewolfe We accept request for community maintained, general packages or popular configurations. Adding individual eslint configs as packages isn't very practical for us (we make exceptions for paying customers). However, in your situation I would recommend using org-wide configurations. You can point to `https://github.com/ndlib/eslint-config-hesburgh` as your org-wide config repo in the UI from houndci.com/repos. For example:
<img width="1241" alt="Screen Shot 2019-03-25 at 10 55 14 PM" src="https://user-images.githubusercontent.com/116327/54974405-2993ad00-4f51-11e9-96bf-91666d515b2b.png">

Note that the config file in the org-wide repo needs to be named the same as the one in `.hound.yml` (and JSON formatted).

Would something like that work for you?

**Comment by danthewolfe** [comment]
@gylaz Thanks for responding. I sort of suspected that you wouldn't be able to an organizational eslint file. I had forgotten about the organization-wide config option. I did have one question that I'm not finding an answer to:

If I enable the organization-wide config, but already have a .hound.yml on an individual project, which one will be used? We have some older projects that are using less strict linting configurations that we're not quite ready to move to our new code standards. I'd like to continue to use their existing configurations while all new project would use the organization-wide config.

**Comment by gylaz** [comment]
With the org-wide config enabled the flow is like this:

- org-wide config is loaded first
- if there is a repo config, it is merged into the org-wide-config, overriding any org-wide rules

The idea is that individual repos typically want to modify a handful of rules, but rely on the parent org-wide to supply the rest.

If the repo config is widely different than the org-wide, then unfortunately, almost a full config file needs to be supplied at the repo level.

**Comment by danthewolfe** [comment]
Thanks for the info. I'll see if I can make that work.
