### ISSUE TITLE
Support for TargetRubyVersion 2.6

### ISSUE THREAD

**Issue by raspygold** [houndci/hound#1680]
We are trying to set Hound to target Ruby 2.6 but it looks like Hound is not compatible with 2.6 due to the version of Rubocop in use currently. Support for targeting Ruby 2.6 was added in Rubocop [v0.60.0](https://github.com/rubocop-hq/rubocop/releases/tag/v0.60.0) and Hound seems to using v0.59.2.

For now we'll set the target Ruby version back to 2.5 until Hound can support 2.6.

**Comment by gylaz** [comment]
Hound supports both Ruby 2.6 and RuboCop version `0.64.0`.
You can read about setting the version here: http://help.houndci.com/configuration/linter-versioning
and check which linter versions we support here: http://help.houndci.com/configuration/supported-linters

Let me know if that helps.

**Comment by yiweig** [comment]
I think we also hit this? Running rubocop 0.62.0, and ran into this error after merging in this change to our `.rubocop.yml`: `TargetRubyVersion: 2.6`. 

<img width="789" alt="Screen Shot 2019-03-19 at 10 39 56 AM" src="https://user-images.githubusercontent.com/6099687/54628972-d6db6200-4a33-11e9-9247-7e86c232e25e.png">

Maybe I'm missing some configs or something, is there anything else I should check?

**Comment by gylaz** [comment]
Are you specifying Rubocop version in your `.hound.yml`?

Current supported versions are 0.54.0 (default), 0.59.2, 0.63.0 , 0.64.0.

Here's how to specify a version: http://help.houndci.com/configuration/linter-versioning

**Comment by yiweig** [comment]
Ah yeah, looks like we weren't explicitly specifying Rubocop version in our `.hound.yml`. Specified `0.64.0` and our `TargetRubyVersion: 2.6` works now. Thanks!
