### ISSUE TITLE
Pull request comments are duplicated

### ISSUE THREAD

**Issue by AMHOL** [houndci/hound#1681]
Hi, we just started using Hound as our previous solution which used [ruby-saddler](https://github.com/packsaddle/ruby-saddler) was duplicating comments, but I see that the same issue is present in Hound CI, is there a way to stop this from happening? For example, we received the following comment after one push, then the same comment was repeated twice on the next push.

![selection_003](https://user-images.githubusercontent.com/1582784/54011240-c06c1580-41ac-11e9-8c24-093880071f4a.png)

I'd much rather not have the comments duplicated.

**Comment by gylaz** [comment]
The comments aren't supposed to be duplicated. Is there a PR that demonstrates this issue?

**Comment by AMHOL** [comment]
@gylaz, not in a public repository, I'll try to replicate in a public repo on Monday.

**Comment by AMHOL** [comment]
@gylaz I attempted to duplicate the error in a public repo but everything worked as expected. Will close this issue and keep an eye out, if it happens again I'll reopen.
