### ISSUE TITLE
Whitelist Request for Rule react/jsx-fragments

### ISSUE THREAD

**Issue by 11mdlow** [houndci/hound#1683]
Hoping to resolve this error we're getting in our private repo: `Definition for rule 'react/jsx-fragments' was not found react/jsx-fragments`

This rule was added in a relatively new version of `eslint-plugin-react`

Thanks!

**Comment by gylaz** [comment]
`react/jsx-fragments` is already whitelisted, but as you mentioned it's in the newer version of `eslint-plugin-react`. We'll be releasing support for the latest ESLint pretty soon, which should include an updated `eslint-plugin-react`.

**Comment by TomasBarry** [comment]
Hi @gylaz, we are experiencing this issue also.

Have you released support for the latest ESLint (or one that supports `react/jsx-fragments`)? If so, what version is it?

**Comment by gylaz** [comment]
@TomasBarry I'm not sure which version added that rule, but try `6.3.0` of ESlint.
