### ISSUE TITLE
Add documentation for SCSS-Lint versioning

### ISSUE THREAD

**Issue by kennyadsl** [houndci/hound#1686]
SCSS-Lint now supports multiple versions. We should update documentation accordlying: 

- [x] add it to [`linter-versioning`](http://help.houndci.com/configuration/linter-versioning)
- [x] add `0.57.1` on the [`supported-linters`](http://help.houndci.com/configuration/supported-linters) along with `v0.50.2` (default).

**Comment by gylaz** [comment]
This is done. Thanks for opening this @kennyadsl!
