### ISSUE TITLE
Why checking for languages that aren't supported ?

### ISSUE THREAD

**Issue by zsubzwary** [houndci/hound#1692]
As mention in the README of Hound repo the language Java is not supported !!
Also in the issue #881 

Then why my Java files are checked and announced as passed ??
![Picture](https://imgur.com/CmYJxxk.jpg)

**Comment by gylaz** [comment]
When Hound has nothing to check, it reports a successful status.

**Comment by zsubzwary** [comment]
Don’t you think this should be mentioned in the README file @gylaz ?? 
# 🤔🤔

**Comment by zsubzwary** [comment]
> a hosted service that reviews GitHub pull requests for **style guide violations.**

Where are the Style guide given ?
Which one do they use ??
Any example please !!??!!

**Comment by gylaz** [comment]
> Don’t you think this should be mentioned in the README file @gylaz ??

We can certainly add a line for this, if you think it'll help. It's never came up as a question before.

> Where are the Style guide given ? Which one do they use ??

Each linter has its own style guide. You can get a lot of the linter information by browsing our [help section](http://help.houndci.com/).

**Comment by zsubzwary** [comment]
Yes @gylaz this should definitely be in there !!
I open a PR ... Let’s see what happens !!
