### ISSUE TITLE
Whitelist eslint-config-cooperka

### ISSUE THREAD

**Issue by cooperka** [houndci/hound#1700]
[eslint-config-cooperka](https://github.com/cooperka/eslint-config-cooperka) is used on [at least 100](https://github.com/search?p=1&q=eslint-config-cooperka&type=Code) open-source projects, including:
- [FaridSafi/react-native-gifted-chat](https://github.com/FaridSafi/react-native-gifted-chat)
- [cooperka/react-native-snackbar](https://github.com/cooperka/react-native-snackbar)
- [LuncSAS/react-native-mapbox-direction](https://github.com/LuncSAS/react-native-mapbox-direction)
- [dgdavid/dose-calculator](https://github.com/dgdavid/dose-calculator)
- [TheCarterCenter/nemo](https://github.com/thecartercenter/nemo)

Could Hound please whitelist it? It's a small config that extends from Airbnb's rules. We appreciate any help you can provide.

**Comment by gylaz** [comment]
This has been whitelisted for a while now, so closing.
