### ISSUE TITLE
Chrome errors when running tests

### ISSUE THREAD

**Issue by jhsu802701** [houndci/hound#1703]
I've installed the chromedriver package with apt-get, but running the "bundle exec rake" command still gives me the following error for multiple tests:
```
      Selenium::WebDriver::Error::UnknownError:
        unknown error: Chrome failed to start: exited abnormally
          (unknown error: DevToolsActivePort file doesn't exist)
          (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
          (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.9.0-8-amd64 x86_64)
```
What critical dependancy am I missing?

**Comment by gylaz** [comment]
I'm not sure. Most of us work on Macbooks, so haven't ran into issues with Linux. Seems like a few others have tried to figure this out over in: https://stackoverflow.com/questions/22558077/unknown-error-chrome-failed-to-start-exited-abnormally-driver-info-chromedri/23673054
