### ISSUE TITLE
[SwiftLint] Excluded files are not excluded actually

### ISSUE THREAD

**Issue by ikesyo** [houndci/hound#1704]
An example is https://github.com/Quick/Nimble/pull/643#discussion_r271702267

- `.swiftlint.yml` is specified as a config file: https://github.com/Quick/Nimble/blob/492fb3bd79d539883ae29d7d88660efef3f24c80/.hound.yml#L2
- `Tests/NimbleTests/XCTestManifests.swift` is excluded: https://github.com/Quick/Nimble/blob/492fb3bd79d539883ae29d7d88660efef3f24c80/.swiftlint.yml#L10

**Comment by gylaz** [comment]
The linter key should be `swiftlint` instead of `swift`. Then your config should be picked up.

**Comment by ikesyo** [comment]
Oh I didn't know that! When the configuration key has changed?

**Comment by ikesyo** [comment]
Looks like https://github.com/houndci/hound/pull/1570 is the cause?
