### ISSUE TITLE
Document and / or add flake8 plugins

### ISSUE THREAD

**Issue by lcannon** [houndci/hound#1707]
Hey, there's a number of flake8 plugins I'd like to add to our config file, but the flake8 config page on hound doesn't list any plugin support, and a test PR I put in appeared to fail due to them missing.

It'd be great if the documentation page would either list the plugins that are supported, or explicitly call out that none are.

Thanks!

(For our purposes it would be awesome to have flake8-pytest, flake8-django and flake8-bugbear)

**Comment by gylaz** [comment]
We can add some of the popular plugins. We typically handle/add plugins on request basis.

**Comment by lcannon** [comment]
Would you like separate tickets added for the above plugins, or is it fine to just leave them in here?

**Comment by gylaz** [comment]
Listing them here is fine.

**Comment by lcannon** [comment]
* [ ] flake8-pytest
* [ ] flake8-django
* [ ] flake8-bugbear

**Comment by viliusddd** [comment]
Hi, when are you planning on adding flake8 plugins? Could you add `flake8-black` also?

**Comment by gylaz** [comment]
We've added support for these plugins.
