### ISSUE TITLE
[SwiftLint] Excluded files are not excluded

### ISSUE THREAD

**Issue by rajkhatri** [houndci/hound#1708]
Hey,

My excluded files are not being excluded, doesn't look like its picking up anything that i add in excluded from the `.swiftlint.yml`

`.swiftlint.yml`:
```
disabled_rules:
  - line_length
  - trailing_whitespace
  - statement_position
excluded:
  - TheRealReal/Networking/GraphQL
```

`.hound.yml`:
```
swiftlint:
  config_file: .swiftlint.yml
```

It still reviews the swift files inside the `TheRealReal/Networking/GraphQL` folder

It used to work, and then one day stopped working.

The files are both at the root directory level. The repo is also a private repo.

**Comment by gylaz** [comment]
About how long ago did it stop working?

**Comment by rajkhatri** [comment]
roughly 5-6 months ago, we were just too lazy to fix it then as the files in that particular directory didn't change often. Now the files in there change almost every PR we open, and it would be nice to ignore it.

We have scripts generate files into that repository that cause almost 30+ hound warnings per PR

**Comment by gylaz** [comment]
Thanks for reporting. I opened a PR to address this: https://github.com/houndci/hound/pull/1709

**Comment by rajkhatri** [comment]
Awesome, thanks a bunch. Once merged, is there anything we need to do to update on our end? (We use hound/swiftlint it through github)

**Comment by gylaz** [comment]
It's been released, so you shouldn't experience the issue anymore. I'm going to close this issue, but let me know if you still see it pop up.
