### ISSUE TITLE
Hound Frequently Stuck "Sniffing Around"

### ISSUE THREAD

**Issue by gregfletch** [houndci/hound#1711]
The last couple of days my organization has been trying to integrate Hound into our CI/CD pipeline (primarily with private repos at this point). And we have noticed frequent occurrences of Hound being "busy sniffing around..." (see screenshot below). At this point, I have not set `fail_on_violations` in the Hound config, nor have I made Hound passing a pre-condition to be able to merge to master, but I would like to be able to do both. However, it is difficult to make Hound enforce if I cannot get it to run reliably. Other than forcing devs to push empty/amended commits to re-trigger Hound to run (which will likely prevent me from being able to have Hound enforce fixes for violations which will lead to developers ignoring violations because it isn't preventing merging), is there anything that can be done to improve the reliability?

**Comment by gylaz** [comment]
It's likely there's a particular issue with the way the repo got setup with Hound. The most reliable way is to install our new [GitHub app](https://github.com/apps/hound) on your repo, as the bot user approach has flaws. You can also reach out to us via the help widget from houndci.com and we can look into your repos particular situation.

**Comment by gylaz** [comment]
The discussion has been moved to our support channel. I'm going to close this.
