### ISSUE TITLE
Whitelist rubocop-performance

### ISSUE THREAD

**Issue by Malaber** [houndci/hound#1718]
Hello, I am receiving the following [error](https://github.com/turniere/turniere-backend/pull/41#pullrequestreview-236738086) from hound-ci after adding rubocop-performance to my project's Gemfile: 

> Some files could not be reviewed due to errors:
> cannot load such file -- rubocop-performance

Could this be whitelisted for hound-ci? Thank you!

**Comment by gylaz** [comment]
Sure thing. Which version of RuboCop are you using with Hound?

**Comment by Malaber** [comment]
Thanks!
```
rubocop (0.69.0)
rubocop-performance (1.3.0)
```

**Comment by Thor77** [comment]
Please whiltelist `rubocop-rails` as well.
It will be removed from `rubocop` in version 0.72 [ref](https://metaredux.com/posts/2019/05/22/a-modular-rubocop.html)

**Comment by gylaz** [comment]
These are now supported in RuboCop 0.71+
