### ISSUE TITLE
Logo usage

### ISSUE THREAD

**Issue by vlcty** [houndci/hound#1721]
I'd like to include the Hound CI logo to a project of mine. It would be displayed along with a link to your homepage. Are there any guidelines and/or am I allowed to use it?

**Comment by gylaz** [comment]
You're more than welcome to!

We have a badge if you'd like to add that to your README:
[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com)

Code for it:
```
[![Reviewed by Hound](https://img.shields.io/badge/Reviewed_by-Hound-8E64B0.svg)](https://houndci.com)
```
