### ISSUE TITLE
Double-Quotes issue on JSX

### ISSUE THREAD

**Issue by graemecode** [houndci/hound#1727]
Screenshot of unexpected HoundCI output:

<img width="905" alt="Screen Shot 2019-07-01 at 5 55 29 PM" src="https://user-images.githubusercontent.com/36094097/60474921-94781280-9c29-11e9-9a12-446d18df687c.png">

Seeing this very consistently, looks like hound is complaining about double-quotes on React code.

hound.yml:
```yml
eslint:
  enabled: true
  config_file: .eslintrc
```

eslint.rc:
```json
{
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "double"]
    }
}
```

**Comment by gylaz** [comment]
Looks like this is with an older version of ESLint (by default it's `4.18.2`).
Could this be an issue with older ESLint? Are you able to try and reproduce it locally?
