### ISSUE TITLE
Invalid "extends" configuration error for TSLint

### ISSUE THREAD

**Issue by jonathanlie** [houndci/hound#1728]
Been receiving this error since we added a third-party TSLint rule.

===
Some files could not be reviewed due to errors:
<details>
<summary>Failed to load tslint.json: Invalid "extends" configuration value - could not...</summary>
<pre>Failed to load tslint.json: Invalid "extends" configuration value - could not require "tslint-lines-between-class-members". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
</pre>
</details>
===

Previously, we could open a PR towards the linter app like this [issue](https://github.com/houndci/hound/issues/1574) to install a new lint rule. What is the action we need to take now?

**Comment by gylaz** [comment]
The action is to request a package to be added via issues or help widget on our site :)

We can certainly get this package added. Just to clarify, it's this one? https://github.com/chinchiheather/tslint-lines-between-class-members

**Comment by jonathanlie** [comment]
I see :)
Yes, its that one, thanks!

**Comment by gylaz** [comment]
Support has been added for this plugin.
