### ISSUE TITLE
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout...

### ISSUE THREAD

**Issue by patrickdavey** [houndci/hound#1729]
Hi,  I'm upgrading to Ruby 2.6.3 and trying to use hound with the project.

Hound is failing with

```
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout...
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in .rubocop.yml, please update it)
```

### .hound.yml

```yaml
ruby:
  config_file: .rubocop.yml

rubocop:
  version: 0.68.0
```

Inside my own `.rubocop.yml` I _do not have the Layout/FirstParameterIndentation line_. I do have:

```yaml
Layout/IndentFirstArgument:
  EnforcedStyle: consistent
```

Any ideas what might be going on here?

**Comment by gylaz** [comment]
It's either `rubocop` or `ruby`, not both. `rubocop` being the newest (`ruby` is legacy).

Try:
```yaml
rubocop:
  version: 0.68.0
  config_file: .rubocop.yml
```

**Comment by patrickdavey** [comment]
HI @gylaz 

I just tried again, with the same failure message.

```yaml
rubocop:
  version: 0.71.0
  config_file: .rubocop.yml
```

### failure message
```
Some files could not be reviewed due to errors:

Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout...
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in .rubocop.yml, please update it)
```

**Comment by gylaz** [comment]
I think we'll need to debug this further, and take a look at your configuration.
Do you have a public repo where this is replicated?
Otherwise, you can use the help widget on our site to share the `.rubocop.yml` file with us.

**Comment by patrickdavey** [comment]
@gylaz I've reproduced the error here -> https://github.com/patrickdavey/test_rubocop/pull/2

The issue as far as I can tell is this: On the `master` branch it's using an older version of `.hound.yaml` and certainly a different version for TargetRubyVersion etc. from what is on the PR branch.

I think if you can make it so that `hound` respects the `.hound.yml` and `.rubocop.yml` etc. from the PR branch then this issue will go away.

**Comment by gylaz** [comment]
Looks like in the test repo/branch, it's flagging `Layout/IndentFirstArgument` correctly since you're not specifying the newer rubocop version.

**Comment by patrickdavey** [comment]
Ah good point.

So, I changed the config to use the newer rubocop version, and indeed the error did go away (https://github.com/patrickdavey/test_rubocop/pull/3)

However, on the private repo with exactly the same hound.yml and rubocop.yml it's failing with the above error (I diff'd them, the files are exactly the same).

Harrumph, not quite sure what to try from here.

**Comment by gylaz** [comment]
Is the repo using org-wide configuration by any chance?

**Comment by patrickdavey** [comment]
Ah very good @gylaz , that was it. We were only using the one-repo anyway, so, I just turned off the `org-wide` rubocop setting and it seems to be working fine now.

Thanks for the quick response :)
