### ISSUE TITLE
Missing eslint-plugin-cypress

### ISSUE THREAD

**Issue by viiqswim** [houndci/hound#1732]
Hi! My team is working with 'eslint-plugin-cypress' and I can't seem to get Hound to recognize that we have it in the `package.json`. I looked around for a bit and saw that Hound needs to whitelist certain eslint plugins. Could we get `eslint-plugin-cypress` whitelisted, pretty please?

[Here is the package github repo](https://github.com/cypress-io/eslint-plugin-cypress)

And here is the hound error
```
Oops! Something went wrong! :(
ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-plugin:cypress/recommended". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make sure eslint-plugin-plugin:cypress/recommended is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm i eslint-plugin-plugin:cypress/recommended@latest --save-dev
If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by gylaz** [comment]
Yes, we'll get it whitelisted. I'll update the issue once it's live.

**Comment by gylaz** [comment]
This has been live for a while, closing.

**Comment by Fiyin-Anne** [comment]
Hello @viiqswim , were you eventually able to fix this? I am currently running into the same error.
```
Oops! Something went wrong! :(
ESLint: 7.7.0
ESLint couldn't find the plugin "eslint-plugin-jsdoc".
(The package "eslint-plugin-jsdoc" was not found when loaded as a Node module from the directory "/tmp/d20201023-6-12b34yx".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm install eslint-plugin-jsdoc@latest --save-dev
The plugin "eslint-plugin-jsdoc" was referenced from the config file in ".eslintrc".
If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

**Comment by viiqswim** [comment]
@Fiyin-Anne I never got it resolved myself, but that's because I moved on a while after I got the message from @gylaz that it had been resolved. I'd follow up with him :)

**Comment by Fiyin-Anne** [comment]
@viiqswim Oh alright, thanks!

**Comment by Fiyin-Anne** [comment]
Hello @gylaz, How do I fix this error pls?

> Hello @viiqswim , were you eventually able to fix this? I am currently running into the same error.
> 
> ```
> Oops! Something went wrong! :(
> ESLint: 7.7.0
> ESLint couldn't find the plugin "eslint-plugin-jsdoc".
> (The package "eslint-plugin-jsdoc" was not found when loaded as a Node module from the directory "/tmp/d20201023-6-12b34yx".)
> It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
>     npm install eslint-plugin-jsdoc@latest --save-dev
> The plugin "eslint-plugin-jsdoc" was referenced from the config file in ".eslintrc".
> If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
> ```

Hello @gylaz, How do I fix this error pls?
