### ISSUE TITLE
Add .ts and .tsx support on ESLint

### ISSUE THREAD

**Issue by brendanoffer** [houndci/hound#1734]
Hi, our project is using ESLint to lint our `.ts` and `.tsx` files. We are doing this because TSLint is [being deprecated](https://github.com/palantir/tslint/issues/4534) and moved to [@typescript-eslint](https://github.com/typescript-eslint/typescript-eslint).

Currently, the hound ESLint parser  is configured to parse `.js .es6 .jsx .vue` files. Would you be open to either including `.ts` and `.tsx` files in the `FILE_REGEXP` or a PR to extend hound's configuration to accept more files extension types?

As an aside, eslint itself only lints `js` files by default. In order to lint your files an `--ext=.ts,.tsx` argument is necessary for ESlint to scan typescript files.

**Comment by gylaz** [comment]
Yes, a PR for this would be welcome.

A few questions that I have regarding support of TS files with Hound and ESLint.

- What happens when we run `eslint foo/bar/baz.ts`? (this is how Hound actually lints each file)
- How do we know if a user wants their TS files linted with ESlint? Can we lint them anyway if typescript-eslint is not present?

**Comment by brendanoffer** [comment]
1) If hound passes a `.ts` file to `eslint` it will lint the file regardless of extension. The issue is that eslint (or hound) will not select or lint these files by default. For example something like `eslint components/` would lint all `js` and `jsx` files but not `ts`. Conversely, if we ran `eslint --ext=.ts,.tsx components/` it would run against the `ts` files.

2a. I believe you'd have to make the file types (extensions) configurable by the user. 
2b. You can lint the ts files without typescript-eslint. The linter would run against the file based on the configured `eslintrc` file. I don't think you would want to prevent this from happening as its possible some users would want to customize which linters and rulesets they use.

**Comment by gylaz** [comment]
The related PR was merged.
