### ISSUE TITLE
Missing @tradegecko/eslint-config-ember dependency

### ISSUE THREAD

**Issue by brookjordan** [houndci/hound#1736]
Hound has been a boon to our linting!

But we're upping our linting game and we're missing a dependency:
`@tradegecko/eslint-config-ember`

<img width="755" alt="Screen Shot 2019-08-21 at 3 14 50 PM" src="https://user-images.githubusercontent.com/9323190/63410763-9c348600-c426-11e9-9d6a-3ebb58b46b5e.png">

**Comment by gylaz** [comment]
Added support for this. Please keep in mind that you'll need to reach out to us if you want to update it to a later version.

**Comment by billybonks** [comment]
Thanks so much :)
