### ISSUE TITLE
"Unable to find gem" when Rubocop inherit_gem points to a bundled private gem

### ISSUE THREAD

**Issue by piao-mdsol** [houndci/hound#1737]
Hi there,

I ran into an error when rubocop's `inherit_gem` points to a private gem, which is bundled into the project. When Hound is run on Github, it comments as:

```
Unable to find gem a_bundled_private_gem; is the gem installed? Gem::MissingSpecError
```

## Context

We're using Rubocop's `inherit_gem` to share common configuration across projects. The shared Rubocop config is made as a gem, hosted on a private Github repo. In each project we add it to our Gemfile and execute it with `bundle exec rubocop` locally, following  [Rubocop's doc](https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md#inheriting-configuration-from-a-dependency-gem).

```yaml
# .rubocop.yml

inherit_gem:
  a_bundled_private_gem: rubocop.yml

# customizations
```

## How to fix?

Is it possible to configure Hound to run it with `bundle exec ` so it can find the bundled private gem? Or could Hound use thegranted  access token to access the private gem..?

This feels like a common use case.. Please let me know if I simply overlooked something obvious. 🙇 

Thanks!

**Comment by gylaz** [comment]
Hound doesn't support private gems, since it's a security concern for us.

**Comment by kinopyo** [comment]
@gylaz Thanks for the reply. We'll seek other options.

**Comment by piao-mdsol** [comment]
@gylaz Thanks for the reply. We'll seek other options.
