### ISSUE TITLE
[Feature request] ESLint 6 Support 

### ISSUE THREAD

**Issue by Jensenks** [houndci/hound#1740]
Is ESLint 6 support in the pipeline?

**Comment by gylaz** [comment]
Yes, we're just wrapping up a few things. I expect we'll release it in the coming week.

**Comment by chadwilken** [comment]
Any update on this? I contacted support last week and was told to file an issue for this, but this seems like it should have been added months ago.

**Comment by gylaz** [comment]
We support a few releases of ESLint 6: http://help.houndci.com/en/articles/2461415-supported-linters
