### ISSUE TITLE
Cannot find module 'eslint-config-prettier/@typescript-eslint'

### ISSUE THREAD

**Issue by brendanoffer** [houndci/hound#1745]
Hello again,

I see the ts and tsx files are starting to be scanned by our eslint. I now need some missing modules added. Is there anyway for myself to do this or do you have to?

```
@typescript-eslint/eslint-plugin
@typescript-eslint/parser
```

![Screen Shot 2019-09-24 at 1 24 21 PM](https://user-images.githubusercontent.com/3682265/65535143-da621100-dece-11e9-9742-d86a25864522.png)

**Comment by gylaz** [comment]
We'll need to add these on our back-end. I'll update here once they are live.

**Comment by Jensenks** [comment]
We are seeing a similar error message:

```
Oops! Something went wrong! :(
ESLint: 6.3.0.
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/tmp/d20190925-6-g2gkp2".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm install @typescript-eslint/eslint-plugin@latest --save-dev
The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in ".eslintrc".
If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by gylaz** [comment]
@ brendanoffer what version of ESLint are you using with Hound?

**Comment by gylaz** [comment]
Released support for this. Let us know if it doesn't work for you still.

**Comment by brendanoffer** [comment]
```
    "@typescript-eslint/eslint-plugin": "^2.3.1",
    "@typescript-eslint/parser": "^2.3.1",
    "eslint": "^6.4.0",
```

**Comment by gylaz** [comment]
@brendanoffer Just FYI, `6.4.0` is not supported yet. See http://help.houndci.com/en/articles/2461415-supported-linters for supported versions.

**Comment by seankwalker** [comment]
Hi, I've been having this same error; pertinent deps are:
```
"@typescript-eslint/eslint-plugin": "2.5.0",
"@typescript-eslint/parser": "2.5.0",
"eslint": "6.3.0"
```

**Comment by gylaz** [comment]
@seankwalker What version of ESLint are you specifying in your `.hound.yml`?

**Comment by seankwalker** [comment]
ah thanks @gylaz, I wasn't specifying a version in `.hound.yml.` I specified `6.3.0` and that worked!

For whatever reason, I had assumed that Hound defaulted to whichever linter version was specified in the `package.json` -- upon reflection, it's a pretty dumb assumption 😛
