### ISSUE TITLE
Errors raised on `.erb` files that are not from ERBLint

### ISSUE THREAD

**Issue by TomasBarry** [houndci/hound#1750]
We have noticed that when submitting a Pull Request with `.erb` files, Hound flags linter errors that are not present when running the linter locally.

As per [your docs](http://help.houndci.com/en/articles/2538835-erb-lint) we are also using `erb_lint` `0.0.28`. Running the linter on an ERB file will return an _all clear_ from ERBLint, however, Hound will raise issues such as:

`Tag img is a void element, it must end with > and not />.`

Having looked in the Hound repo, I suspected that this may be down to `coffeelint` being run on ERB files (see the regex [here](https://github.com/houndci/hound/blob/master/app/models/linter/coffeelint.rb#L5)). However, we have explicitly disabled `coffeelint`. Here is a snippet of our `.hound.yml` file:

```yml
...
coffeescript:
  enabled: false

erblint:
  enabled: true
...
```

Per the [docs](http://help.houndci.com/en/articles/2138490-coffeelint) this is the correct way to disable `coffeelint`.

Any ideas as to what could be happening here? I have confirmed that we are also using `erb_lint` `0.0.28` (and not the latest release) and I have confirmed that neither `erb_lint` being run in the command line, or using ERBLint through the [Sublime Plugin](https://packagecontrol.io/packages/SublimeLinter-contrib-erblint) flags the issues raised by Hound on the Pull Request.

**Comment by James-Bovis** [comment]
This has been so annoying when raising PR's. Would like to see this fixed soon.

**Comment by TomasBarry** [comment]
Any feedback from maintainers on this one?

**Comment by gylaz** [comment]
The docs were outdated and Hound is actually running `0.0.29`. Can you try it with that version?
I am seeing this error with a simple (v0.0.29):
```sh
echo "<img/>" > foo.erb
erblint foo.erb
```

**Comment by TomasBarry** [comment]
@gylaz, yep that was the issue. Thanks for updating the docs too.
