### ISSUE TITLE
Support for eslint-plugin-sonarjs

### ISSUE THREAD

**Issue by hueyy** [houndci/hound#1751]
Could I request that the following plugins be whitelisted?

* [`eslint-plugin-sonarjs`](https://github.com/SonarSource/eslint-plugin-sonarjs)
* [`eslint-plugin-no-secrets`](https://github.com/nickdeis/eslint-plugin-no-secrets)
* [`eslint-plugin-simple-import-sort`](https://github.com/lydell/eslint-plugin-simple-import-sort)

**Comment by gylaz** [comment]
Support for these plugins has been added in ESLint v6.8.0.
