### ISSUE TITLE
Hound with rubocop 0.75.0 does not read rubocop.yml

### ISSUE THREAD

**Issue by sbeam** [houndci/hound#1761]
Noticed that Hound seems to have reverted to the default config for Rubocop on an existing project, after upgrading 0.53 -> 0.75

<img width="740" alt="Screenshot: hound and rubocop config" src="https://user-images.githubusercontent.com/33286/70479119-af896100-1aaa-11ea-992c-4ebff6a194df.png">

<img width="749" alt="Screenshot: Hound error on github" src="https://user-images.githubusercontent.com/33286/70479123-b2845180-1aaa-11ea-8b64-0208075499c2.png">

But, I made a very simple test project, and having the same problem. `.rubocop.yml` has a LineLength of 90, and locally, no offenses. Hound enforces length of 80.

https://github.com/sbeam/houndy-hound/pull/1

**Comment by gylaz** [comment]
Hi @sbeam!

You are using both `ruby` and `rubocop` keys in your `.hound.yml`.
Hound will look for one or the other, but not both.
`ruby` is the legacy key, and `rubocop` is the new style.

Try:
```yaml
fail_on_violations: true

rubocop:
  config_file: .rubocop.yml
  version: 0.75.0
```

**Comment by sbeam** [comment]
@gylaz aggh! I was wondering why there was both! thanks so much :)
