### ISSUE TITLE
Linter service location

### ISSUE THREAD

**Issue by JensDebergh** [houndci/hound#1767]
Hey there!

Thank you for creating this amazing project. I haven't been able to follow-up on all the recent changes hound has been through but I remembered this excellent piece of software from a couple of years ago and tried to test it out.

As I understand all linting services have been extracted from the main app, but where do I found these linter services? (are they closed source?). Links inside the README lead to pages we don't have access too.

I don't mean to bash the project, I'm just clueless on where to find the available linters that process the background queues.

If these services are closed source I understand since you guys have to make money too.

Kind regards
Jens

**Comment by gylaz** [comment]
Hi @JensDebergh,

Yes, the linters service is closed source. We made that decision to protect ourselves financially. We probably need to fix those broken links in the README.
