### ISSUE TITLE
"Black would make changes" (flake8-black?)

### ISSUE THREAD

**Issue by boegel** [houndci/hound#1769]
@houndci-bot posted a puzzling comment in a recent PR in our (Python) repo: https://github.com/easybuilders/easybuild-framework/pull/3156/files#r364740161

It looks like this is coming from [flake8-black](https://github.com/peterjc/flake8-black), but the comment is pretty useless (that's putting it mildly).

Is there a way to make the comment more meaningful?
Is `flake8-black` now enabled by default in Hound CI? Can it be disabled?

**Comment by gylaz** [comment]
Yes, we recently added `flake8-black` due to numerous requests, and unfortunately it is enabled by default. However, you can choose to ignore its "validation codes", like so...

Add a `.flake8` file to your project if doesn't exist already and configure it to ignore the BLK codes:

```
[flake8]
ignore = BLK100
```

You can add other codes listed in https://pypi.org/project/flake8-black/ if you'd like.

Then you need to tell Hound about your Flake8 config by adding it to `.hound.yml` file:

```
flake8:
  enabled: true
  config_file: .flake8
```

as documented here http://help.houndci.com/en/articles/2138537-flake8

Hope this helps!

**Comment by boegel** [comment]
@gylaz Thanks for the info!

Do you know if there's a way to figure out what `black` would change, i.e. to make @houndci-bot report that?

**Comment by gylaz** [comment]
I'm not sure if there's a way, but unfortunately, I don't have Python expertise and https://pypi.org/project/flake8-black/ is all I referenced for this issue.

**Comment by myfashionhub** [comment]
I end up just disabling it because it complains about a perfectly fine line of code
```python
status_callback = config.get('services.relay.{}.callbackUrl'.format(provider_name), None)
```
It wants me to use double quotes?

**Comment by boegel** [comment]
Closing now since it's clear how to avoid that @houndci-bot posts these comments.

**Comment by Flamefire** [comment]
Black needs a separate config (see their docu) and most prominent issues are line length (doesn't pick up the flake8 param as it seems) and quote unification

**Comment by Flamefire** [comment]
@gylaz doesn't seem to work: https://github.com/easybuilders/easybuild-easyblocks/blob/483bc9f90f80a718936e20417a0178477764f257/.hound.yml + https://github.com/easybuilders/easybuild-easyblocks/blob/483bc9f90f80a718936e20417a0178477764f257/setup.cfg#L18 still results in a remark https://github.com/easybuilders/easybuild-easyblocks/pull/1901#discussion_r366902196

**Comment by gylaz** [comment]
@Flamefire It looks like at the time when Hound made that comment, your flake8 config did not ignore the Black rule yet: https://github.com/easybuilders/easybuild-easyblocks/blob/b08d137aeb2b02b4ddb9cd75beea0fa11bf6575c/setup.cfg

**Comment by Flamefire** [comment]
I don't understand. The comment is from yesterday, https://github.com/easybuilders/easybuild-easyblocks/pull/1923 which added the ignore was merged 2 days ago.

**Comment by yelizariev** [comment]
This works for me: https://github.com/it-projects-llc/svalka/commit/37ff94ce78646192bd362151a145cb29f3c6a6b2#diff-161c65d438d330a5a8428782bb4340e0

(I use organization-wide config: https://github.com/it-projects-llc/svalka/blob/d3873ded77e105d37d8b2909c34457ccbca4f74f/.hound.yml#L21-L23 )

**Comment by boegel** [comment]
@Flamefire The branch used in https://github.com/easybuilders/easybuild-easyblocks/pull/1901 was not synced with` develop` after https://github.com/easybuilders/easybuild-easyblocks/pull/1923 was merged, Hound picks up the `setup.cfg` from the branch used for the PR (not the target branch).

**Comment by Flamefire** [comment]
Ah ok, understood. Thanks!

**Comment by dliu-fn** [comment]
I had a breakpoint in my code. Took it out, and then a line-number showed up.
