### ISSUE TITLE
Hound encountered an error: how to get more info?

### ISSUE THREAD

**Issue by boegel** [houndci/hound#1772]
The @hound-bot test in https://github.com/easybuilders/easybuild-framework/pull/3168 is failing with `We've encountered an error while reviewing your code.`, but there are no details available on what the issue is...

Are there known issues with the Hound CI service currently, or is the problem specific to that PR somehow (and if so, how can I figure out what the problem is)?

**Comment by gylaz** [comment]
It was likely a one-off failure (maybe network issue). I re-ran the build and it passed.

**Comment by boegel** [comment]
It happened twice, I re-triggered the test shortly after by closing an re-opening the PR.
Good to hear it seems resolved now though, could very well have been a temporary fluke...
