### ISSUE TITLE
Bump RuboCop version to 0.80.1

### ISSUE THREAD

**Issue by owst** [houndci/hound#1785]
RuboCop 0.80.1 [was released](https://github.com/rubocop-hq/rubocop/releases/tag/v0.81.0) two weeks ago - can Hound please be updated to support it? As per [this page](http://help.houndci.com/en/articles/2461415-supported-linters) the latest supported version is 0.80.0

Thanks!

**Comment by owst** [comment]
Bump - any update on this please?

**Comment by gylaz** [comment]
Thanks for the bump. We'll try to release an updated version in the next week or so.

**Comment by Draiken** [comment]
Bump!

0.82.0 is already out

**Comment by gylaz** [comment]
We've released support for RuboCop `0.83.0`.
