### ISSUE TITLE
whitelist `rubocop-airbnb`

### ISSUE THREAD

**Issue by rezcodes** [houndci/hound#1787]
Thanks for the great platform, could you please whitelist `rubocop-airbnb`?

**Comment by xcskier56** [comment]
Longtime HoundCI fan here. I'm using `rubocop-airbnb` and `rubocop-sorbet`. Would it be possible to whitelist these? 

Thank you!

**Comment by johncsnyder** [comment]
+1

**Comment by aguynamedben** [comment]
+1

**Comment by gylaz** [comment]
It looks like the latest [`rubocop-airbnb`](https://rubygems.org/gems/rubocop-airbnb) gem only works with Rubocop `~> 0.76.0`, which is [rather old](https://github.com/rubocop-hq/rubocop/releases/tag/v0.76.0).

Is the request here to support `0.76.0` version of Rubocop with this gem?

**Comment by aguynamedben** [comment]
We're running on a specific commit we chose on master. It looks like they've made the right changes in the library but haven't pushed the changes as a new version to RubyGems.

```
falcon!ben:/Users/ben/code/mammoth$ bundle info rubocop-airbnb
  * rubocop-airbnb (3.0.2 f81ebad)
        Summary: Custom code style checking for Airbnb.
        Homepage: https://github.com/airbnb/ruby
        Path: /Users/ben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/ruby-f81ebad738c1/rubocop-airbnb
```

https://github.com/airbnb/ruby/issues/176

Related: https://github.com/airbnb/ruby/pull/178

**Comment by gylaz** [comment]
We have added support for `rubocop-airbnb` to RuboCop v0.80.0, as that's the latest version they support.
