### ISSUE TITLE
Hound not finding violations

### ISSUE THREAD

**Issue by diogoscf** [houndci/hound#1792]
I have a repo where I'm trying to set up hound. I opened a [PR](https://github.com/diogoscf/github-lines/pull/2) with deliberate style violations, and Hound failed to detect them. Running `eslint` locally does display errors, and I know Hound is set up since it says all checks have passed. What am I doing wrong?

**Comment by gylaz** [comment]
@diogoscf The file should be with a leading `.`, like `.hound.yml`. Try that and it should get picked up.

**Comment by diogoscf** [comment]
Ah yes it works now! Thanks for the help!
