### ISSUE TITLE
Bump RuboCop version to 0.85

### ISSUE THREAD

**Issue by owst** [houndci/hound#1798]
RuboCop 0.85 was [released](https://github.com/rubocop-hq/rubocop/releases/tag/v0.85.0) two days ago - it'd be great to use the latest-and-greatest in Hound - can the supported RuboCop version be upped to 0.85?

Thanks!

**Comment by owst** [comment]
Bump - RuboCop 0.86 was [released](https://github.com/rubocop-hq/rubocop/releases/tag/v0.86.0) yesterday - can this version be supported in Hound please?

Thanks!

**Comment by Yanchek99** [comment]
Bump Rubocop is now on 0.87.1 [release](https://github.com/rubocop-hq/rubocop/releases/tag/v0.87.1)

**Comment by Yanchek99** [comment]
Bump - Rubocop is now on 0.88.0 [release](https://github.com/rubocop-hq/rubocop/releases/tag/v0.88.0)

**Comment by gylaz** [comment]
We released support for RuboCop `0.88.0`.
