### ISSUE TITLE
Bump RuboCop version to 0.90

### ISSUE THREAD

**Issue by owst** [houndci/hound#1811]
RuboCop 0.89 was [recently released](https://github.com/rubocop-hq/rubocop/releases/tag/v0.89.0)- it'd be great to use the latest-and-greatest in Hound - can the supported RuboCop version be upped to 0.89?

Thanks!

**Comment by owst** [comment]
Bump - 0.90 is [now available](https://github.com/rubocop-hq/rubocop/releases/tag/v0.90.0)

**Comment by mwean** [comment]
0.88 has a bug that's fixed in 0.89: rubocop-hq/rubocop#8714

**Comment by owst** [comment]
I'm not sure when it changed, but as of today [this page](http://help.houndci.com/en/articles/2461415-supported-linters) lists 0.91.0 as being supported
