### ISSUE TITLE
Ruby standard linter and Hound

### ISSUE THREAD

**Issue by lunohodov** [houndci/hound#1836]
It has been a while since thoughtbot moved toward standard: thoughtbot/guides#606 and has also pushed it to thoughtbot/suspenders#1043 ❤️ 

Are there plans to integrate it also in Hound?

**Comment by gylaz** [comment]
It was on our roadmap, but we'll certainly consider adding support for it.

**Comment by shayani** [comment]
Is there any news regarding the support of Standard? Thanks
