### ISSUE TITLE
module flake8 not found

### ISSUE THREAD

**Issue by sparky005** [houndci/hound#1839]
We just started seeing this error in our pipelines that the flake8 module can't be found. We haven't changed our .hound.yml file in over a year so I'm not sure what could have broken

```
Traceback (most recent call last):
  File "/home/linters/.local/bin/flake8", line 5, in 
    from flake8.main.cli import main
ModuleNotFoundError: No module named 'flake8'
```

**Comment by loren-peace** [comment]
We have seen that same problem start appearing late yesterday as well.

**Comment by boegel** [comment]
We are observing the same problem in the [EasyBuild](https://github.com/easybuilders) repositories .

**Comment by salbertson** [comment]
@sparky005 we are working on it, thank you for letting us know! I'll share here when I have an update.

**Comment by sparky005** [comment]
Glad to hear it, thanks @salbertson!

**Comment by salbertson** [comment]
@sparky005 we rolled back a minor change that could have caused the issue. Let me know if you're still seeing the error so we can nail down the cause.

**Comment by sparky005** [comment]
@salbertson Just tested it out and that has fixed the issue! Thanks!
