### ISSUE TITLE
Cannot terminate account

### ISSUE THREAD

**Issue by hlascelles** [houndci/hound#1861]
Hi Hound, we were using your paid for cloud service, but have since moved on to other things. We have disabled your access to our repo, and deleted the webhooks. 

Unfortunately we are still being charged every month. We've tried getting in touch with you via new emails, replies to emails you have sent us and tweeting you (the recommended way) but are receiving no reply.

We are left with this unorthodox method, rather than stop our card and all the pain that involves. I apologise to those using this repo for technical issues!

Is there a good way to get in contact with the company?

**Comment by gylaz** [comment]
@hlascelles I've gone ahead and made sure your account cancellation was addressed. We've also refunded the last charge. In the future, if there's no response feel free to email me directly at greg@hounci.com.
