### ISSUE TITLE
Review commits outside of Pull Requests

### ISSUE THREAD

**Issue by mariusbutuc** [houndci/hound#271]
Can Hound be configured to review GitHub commit pushes instead of pull requests?

**Comment by leenasn** [comment]
+1 because we follow Mainline development. Would you be accepting a pull request for the same? Thanks.

**Comment by Nowaker** [comment]
+1

**Comment by jflowers45** [comment]
+1 - I'm on a team of 3 ... we all just commit when we're ready, no PRs.  We can lint our SCSS locally but would be great to use hound.

**Comment by gylaz** [comment]
We don't have any plans on supporting this in the near future. When we come around to re-evaluating this, we'll reference this issue.
