### ISSUE TITLE
PHP?

### ISSUE THREAD

**Issue by blainesch** [houndci/hound#313]
I see a pull request for coffee-lint. Would you guys be interested in other languages such as PHP? I had an idea to do this for PHP and created a little demo app that is working for a private repo, but this repo is much more extensive and well rounded I'd much rather enable it here then start my own repo or have a diverged fork. Lemme know what you guys think!

**Comment by salbertson** [comment]
@blainesch thanks again for all the work you put into https://github.com/thoughtbot/hound/pull/495.

Any interest in writing a PHP service for Hound, similar to https://github.com/thoughtbot/hound-scss or https://github.com/thoughtbot/hound-go?

**Comment by blainesch** [comment]
How fun! I'd love to.

**Comment by blainesch** [comment]
@salbertson is there a walkthrough on how the core and sub repos work together?

**Comment by salbertson** [comment]
@blainesch no, not yet.

The best way would be to take a look at services for [SCSS](https://github.com/thoughtbot/hound-scss), [Swift](https://github.com/thoughtbot/hound-swift), [Python](https://github.com/thoughtbot/hound-python) or [Go](https://github.com/thoughtbot/hound-go) to get an idea what is needed.

I would also take a look at the changes on the Hound side for [SCSS](https://github.com/thoughtbot/hound/commits/master/app/models/style_guide/scss.rb), [Swift](https://github.com/thoughtbot/hound/commits/master/app/models/style_guide/swift.rb), [Python](https://github.com/thoughtbot/hound/commits/master/app/models/style_guide/python.rb) or [Go](https://github.com/thoughtbot/hound/commits/master/app/models/style_guide/go.rb).

Let me know if you have any questions, I'm happy to help. A few of us hang out in [Slack](http://slack.houndci.com/) as well.

**Comment by salbertson** [comment]
@bernerdschaefer @jakecraige @jmcarp any chance you want to add something to [contribution instructions](https://github.com/thoughtbot/hound/blob/master/CONTRIBUTING.md) on how you added new language services to Hound? A simple PR as a starting point would be great.

**Comment by jakecraige** [comment]
@salbertson I think we still need to refactor the Hound repo a bit so that we don't need so many modifications here to support another service. I've discussed this with a few people and think it would be beneficial for future integrations(not sure if there's a card for it?) 

I do think some initial docs could be helpful for how it's actually implemented through redis, while leaving out some details about hound modifications until we solidify how they are done. I know @teoljungberg is also working on an integration so he may be able to contribute.

Personally, I don't think I'll have time to write them up myself soon, lots of other things I want to focus on(hound-swift and other investment projects) first.

For @blainesch the PRs themselves may be helpful to see full diffs of the changes required

Swift PR: https://github.com/thoughtbot/hound/pull/896
Go PR: https://github.com/thoughtbot/hound/pull/852
Scss PR: https://github.com/thoughtbot/hound/pull/832
Python PR: https://github.com/thoughtbot/hound/pull/853

**Comment by thorncp** [comment]
@jakecraige some of that work was done in https://github.com/thoughtbot/hound/pull/913

**Comment by jakecraige** [comment]
@thorncp I missed that. Thanks! that's exactly what I was talking about. Carry on with creating docs...

**Comment by potherca** [comment]
Can anyone tell me what the status of this is? Is anybody (@blainesch?)  working on this?

Is there anything blocking this issue from being picked up?

**Comment by blainesch** [comment]
@potherca I have no plans to work on this.

**Comment by potherca** [comment]
At [my current employers](/nerds-and-company) we really likes HoundCI. The lack of PHP (and #1008 Bash/Shell support) is a bit of downer for us.

If no-one else is on this, we might have plans of adding support ourselves.

**Comment by jakecraige** [comment]
@potherca There were some [preliminary docs](https://github.com/thoughtbot/hound/blob/master/CONTRIBUTING.md#writing-a-linter) added for writing a linter and then the examples above. If you end up writing this, we're here and in http://slack.houndci.com/ to help out with any questions.

**Comment by gylaz** [comment]
We've decided not to support PHP in the near future.

**Comment by jbrooksuk** [comment]
https://styleci.io is an alternative which does, plus it fixes your code rather than commenting on it :)

**Comment by gylaz** [comment]
Would love to add support for this soon. Can anyone recommend a leading PHP linter that Hound should support?

**Comment by Potherca** [comment]
The de-facto code scanner is [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer). It comes with a set of standards pre-installed and has the ability for users to add their own code-sniffs.

**Comment by salbertson** [comment]
https://github.com/houndci/hound/pull/1638

**Comment by gylaz** [comment]
[PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) linting is now supported and can be enabled via `.hound.yml`.
```yaml
phpcs:
  enabled: true
```

**Comment by salbertson** [comment]
@Potherca https://github.com/houndci/hound/issues/313#issuecomment-440537534
