### ISSUE TITLE
[Feature] Run hound on templates

### ISSUE THREAD

**Issue by rupurt** [houndci/hound#331]
Howdy,

Is it possible to run hound on templates e.g. `.erb`, `.haml`...

**Comment by gylaz** [comment]
Hound now supports reviewing HAML (in beta).
To enable it add this to your `.hound.yml`:
```yaml
haml:
  enabled: true
```

**Comment by ckundo** [comment]
:tada:

**Comment by salbertson** [comment]
Annnd we will soon support ERBLint too! https://github.com/houndci/hound/pull/1641

**Comment by salbertson** [comment]
Hound now reviews ERB files. https://github.com/houndci/hound/issues/1599#issuecomment-440537267 💥
