### ISSUE TITLE
Objective-C Language Support

### ISSUE THREAD

**Issue by Ashton-W** [houndci/hound#445]
Fairly obvious, hasn't been much chatter about it.

Using [ClangFormat](http://clang.llvm.org/docs/ClangFormat.html) would be nice:
> clang-format ... can be used to format C/C++/Obj-C code.   

It has it's own config format too `.clang-format`.

Unless [Uncrustify](http://uncrustify.sourceforge.net) is more compelling for some reason?

objc

**Comment by guidomb** [comment]
Is there any progress on this issue? I would like to add support for oclint

**Comment by gylaz** [comment]
There has been no progress from the thoughtbot team on this. We've currently paused addition of other languages, while we re-design some of our architecture.

**Comment by thorncp** [comment]
The architecture for this to exist is now in-place, but I wonder if there's still demand for obj-c. As an outsider, it seems like Swift linting is in higher demand. Any thoughts from @thoughtbot/ios ?

**Comment by jakecraige** [comment]
@thorncp Seems like for internal greenfield projects, we'd probably prefer to have Swift since that's what we'll be using. For existing projects that have obj-c, it would be nice for them to have the option to have linting. It seems like it will be awhile before we never need to write obj-c anymore.

IMO Swift is a priority but it would likely be beneficial to have obj-c at some point as well.

**Comment by Ashton-W** [comment]
If the implementation uses clang tools it could be expanded to both fairly easily

**Comment by gfontenot** [comment]
I think we should prioritize Swift, and then look at this. We've been talking about using [SwiftLint][] for Swift linting, so I'm not sure that the solution will scale (I also don't think it _needs_ to scale to Obj-C, and that it's totally reasonable to have two different focused services).

[SwiftLint]: https://github.com/realm/SwiftLint

**Comment by gylaz** [comment]
Hound supports Swift now, but we don't have a lot of interest in supporting Obj-C. I'm closing this, until there's interest internally.
