### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by brentlintner** [houndci/hound#610]
It would quite lovely to have support for TypeScript style checks.

Currently there is [tslint](https://github.com/palantir/tslint).

**Comment by brentlintner** [comment]
If this is desired, I might try and do this in my spare time if no one else picks it up.

It seems there is no gem based wrapper for `tslint`. Given that, I am interested in what might be an ideal way to implement a `StyleGuide::TypeScript` class. Attempting to create a gem to wrap `tslint` seems like the most prudent path. :-)

**Comment by rauluranga** [comment]
+1

**Comment by gylaz** [comment]
We don't have plans in the near future to support TypeScript.
