### ISSUE TITLE
prefer `x` over `x` in Hound, but works in Rubocop

### ISSUE THREAD

**Issue by lowjoel** [houndci/hound#725]
After #717, Rubocop configs are inherited (somewhat).

coursemology/coursemology2#120 is a PR where we use `reduce`. That is the Rubocop default, and was overridden in our configuration (via an `inherits_from` directive). Running Rubocop doesn't give any warnings with that line; however the PR does have Hound commenting on it (search the comments for 'houndci').

**Comment by lowjoel** [comment]
And after more attempts, in Coursemology/coursemology2#128, it appears that the configuration merging ignores hashes more than one level deep. I'm not sure if this is something involving Rubocop, or is because of Hound's extra settings.

**Comment by gylaz** [comment]
There hasn't been any recent reports of this issue. Closing.
