### ISSUE TITLE
Option to replace hound's default style guide(disable the merging of configs)

### ISSUE THREAD

**Issue by jakecraige** [houndci/hound#868]
If I remember correctly, the current way config for custom style guides is merged with Hound's defaults.

What do you think about having an option in the `.hound.yml` to disable merging on a per style guide basis?

This would allow individuals or companies with their own custom rubucop config(or whatever linter) to drop it in and disable the defaults so they don't have to provide inverse options for hound's defaults to disable them.

**Comment by gylaz** [comment]
I'm reluctant to add arbitrary options to config. I think we need to make a larger decision about configuration. More discussion about his is in https://github.com/thoughtbot/hound/issues/576

**Comment by salbertson** [comment]
@jakecraige would removing the default Hound configuration help? We've talked about removing Hound overrides and simply using RuboCop defaults and merging those with any custom config in the repo.

**Comment by elwayman02** [comment]
This is really unexpected behavior.  We should be able to provide our own config and have only that config respected (plus the defaults that run in the CLI version of the particular tool). +1 to removing the hound config

**Comment by jakecraige** [comment]
@salbertson Since projects I work on typically mostly follow the thoughtbot conventions it's not a big deal for me. This perhaps gets back to the UI configuration story a bit. We wouldn't want to remove it completely because then every repo would have to define the hound config which could be annoying. 

As a starting point, It could be nice to have config for repos where you could select thoughtbot style guide, rubocop or no style guide on a per repo basis. Ideally this would be in the web UI or configurable via the `.hound.yml` file. `.hound.yml` seems like a great place to start and get something deployed since there is no UI for config yet.

**Comment by thorncp** [comment]
To be extra clear, Hound currently has two "defaults" and it [picks one](https://github.com/thoughtbot/hound/blob/master/app/models/default_config_file.rb#L14-18) based on whether or not the repo is part of the thoughtbot organization.

I suspect the vast majority of repos that want or expect the thoughtbot style guide config are repos under the thoughtbot org. For a short term solution, we can probably remove the non-thoughtbot default without much disruption:

* For the external repos that _do_ want the thoughtbot config (mostly our clients?), we can provide a link to the thoughtbot default file which can be pulled into the repo and used as a normal, e.g. `ruby.yml`, config file.
* For other repos that don't care about thoughtbot defaults, they would then be merging with RuboCop defaults as they expect.

Thoughts?

**Comment by elwayman02** [comment]
@thorncp Please remove the non-thoughtbot default...right now project configs aren't even being respected by hound, the defaults are overriding anything we specify in our configs. See #879 & #870 for examples.

**Comment by jakecraige** [comment]
@elwayman02 I have a project that's not under the thoughtbot org with custom config for ruby and javascript that is being respected so I don't think that statement is completely accurate.

@thorncp I didn't realize it did that. Neat. Yeah I suppose manually adding the tbot config isn't a big deal for client projects.

In relation to other projects, it seems that the option to not do any merging would be useful for people who want to specify completely custom configs without having to figure out how to disable rubocop defaults.

**Comment by elwayman02** [comment]
@jakecraige is it a public project? I would love to see your config or have your thoughts on why my config in #879 is not correct.

**Comment by jakecraige** [comment]
@elwayman02 It's not public but here's a gist of the config I'm using. https://gist.github.com/jakecraige/fd918d670734b273f76a

The only significant difference I see is that I used the recommended file names for both.

**Comment by elwayman02** [comment]
@jakecraige that could be the bug, then.  Maybe Hound isn't respecting custom config names (ie the defaults expected by the linters themselves)?  I'm not sure why Hound doesn't simply recommend `.jshintrc`, `.scss-list.yml`, etc...

**Comment by tansaku** [comment]
I'm experiencing some very weird things from hound seeming not to respect rubocop config.  I was just experimenting with updating my config to use the "recommended" file names, but that hasn't fixed my issue:

https://github.com/makersacademy/airport_challenge/pull/216

at the moment I can only get hound to flag violations when I completely remove all config.  I totally agree with @elwayman02 that the recommended filenames should be the defaults from the actual projects themselves.  When they are not it means we have to do additional set up locally ...

**Comment by gylaz** [comment]
We're working to simplify configuration and remove Hound's defaults. See issue #576.
