### ISSUE TITLE
Support for JavaScript Standard Style (and semistandard)

### ISSUE THREAD

**Issue by joaocunha** [houndci/hound#946]
Both [Feross' Standard](https://github.com/feross/standard) and [Flet's Semistandard](https://github.com/Flet/semistandard) are gaining a lot of traction in the community.

I see `eslint` support [is on the backlog](https://github.com/thoughtbot/hound/issues/738#issuecomment-105822725), so I thought it would make sense to start a discussion around this integration.

**Comment by teoljungberg** [comment]
Hello @joaocunha, I'm currently refactoring the internals of Hound to ease adding other linters than one per language.
We could be interested in both of those projects, but I think it makes sense to do them further down the line.

What do you think?

**Comment by marcbachmann** [comment]
The easiest solution would be to install the [eslint-config-standard](https://github.com/feross/eslint-config-standard) config.
Do you want to extend your plugins or should I just use the `eslintrc` [config the module exposes](https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json)?

**Comment by marcbachmann** [comment]
Oh, that module also has peerDependencies on `eslint-plugin-promise` and `eslint-plugin-standard`.

**Comment by teoljungberg** [comment]
Hound already has the standard config installed via ESLint - https://github.com/houndci/eslint/commit/6171864bb63bb5a50b7259fdeafb53b14fdfdc9a.

So you should be able to use it by including:

```
{
  "extends": "standard"
}
```

into your `.eslintrc`.

Does this solve your issue? @marcbachmann and @joaocunha

**Comment by joaocunha** [comment]
@teoljungberg I for one would be more interested in Semistandard, but it's nice seeing Standard support is available. :+1: 

Do you want me to close this issue and open a separate one for tackling Semistandard in the future?

**Comment by teoljungberg** [comment]
@joaocunha The semistandard is already included in the `eslint` support. So looks like we resolved that already! :tada: 

Please try it out and let us know how it is, and file reports to [hound-eslint](/houndci/eslint)
